### ISSUE TITLE
Proto Grabber is deleting hyperion-remote effect in source list

### ISSUE THREAD

**Issue by crazy888** [hyperion-project/hyperion.ng#1106] opened 2020-12-04 10:46 UTC
- [x] I confirm that this is an issue rather than a question.

## Bug report
When having hyperion-remote effect active with priority 112 and turning on my TV the Android TV Grabber starts sending Input with PROTO port 19445 and priority 100.
When Proto port starts sending the hyperion-remote effect is deleted from the source list.
Afer turning off the TV the Proto port is closed and the hyperion-remote effect is still gone.

Why is the effect deleted when Proto sending starts?

#### Steps to reproduce
1. Start effect with hyperion-remote.
2. Start Android TV Grabber
3. Effect is deleted when TV Grabber starts.

#### What is expected?
I want the effect to stay in source list and become activ again, when proto port is closed.

#### What is actually happening?
The effect is deleted from the source list.

#### System

Hyperion Server: 
- Build:           master (GitHub-08edd880/a42aae44-1606253282)
- Build time:      Dec  1 2020 22:18:15
- Git Remote:      https://github.com/hyperion-project/hyperion.ng.git
- Version:         2.0.0-alpha.9
- UI Lang:         auto (BrowserLang: de-DE)
- UI Access:       default
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 5 (v7l)
- CPU Type:       Raspberry Pi 2 Model B Rev 1.1
- CPU Revision:   a21041
- CPU Hardware:   BCM2835
- Kernel:         linux (5.4.72-v7+ (WS: 32))
- Qt Version:     5.11.3
- Python Version: 3.7.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

**Comment by Paulchen-Panther** [comment] 2020-12-04 11:20
Thanks for your feedback We'll look into the problem at the next opportunity.

Paulchen panther

**Comment by Lord-Grey** [comment] 2021-08-04 15:01
@crazy888 Would you mind checking with alpha 10, if the problem still exists?
I am not able to reproduce it now....

**Comment by Paulchen-Panther** [comment] 2021-10-02 10:24
Closing, as no feedback provided. Can be reopened, if needed.

**Closed by Paulchen-Panther** 2021-10-02 10:24 UTC
Labels: needs investigation
