### ISSUE TITLE
Hyperbian support for HDMI direct input module based on tc358743 on RPI 3/4/zero

### ISSUE THREAD

**Issue by Foamier** [hyperion-project/hyperion.ng#1140] opened 2021-01-09 08:55 UTC
## Feature request
Originally I got introduced to the tc358743 HDMI capture hardware module through the excellent https://pikvm.org/ project.
Here a module with the HDMI to RPI camera port module is used to to remove the need of conversion to analog and usb video capture boards.
Can Hyperbian support the use of this type of card?

Board for RPI3/4 available here:
https://www.aliexpress.com/item/4000102166176.html

Board for RPI3/4/Zero available here:
https://www.aliexpress.com/item/4000152180240.html

#### What problem does this feature solve?
Simplified HDMI direct input on RPI3/4/zero

#### What does the proposed API look like?
Hyperbian to have hardware configuration settings documented if the use of these HDMI capture boards is already supported.

#### How should this be implemented in your opinion?
Since this hardware is already supported by v4l2 and kernel, some documentation around getting it to work would be great.

#### Are you willing to work on this yourself?
Can support with testing.

**Comment by kolyshkin** [comment] 2021-01-10 19:27
> used to to remove the need of conversion to analog and usb video capture boards

1. There is no need for HDMI to analog conversion device anymore, there are plenty of HDMI capture devices available now (e.g. search for rullz).

2. The hardware you refer to should be supported (as long as its driver implements v4l2, which I'm 99.5% sure). The downside might be that downscaling is done in software, which might make the solution not suitable for low cpu power devices (e.g. Pi Zero).

Feel free to give this device a try and report back.

**Comment by andrewpros** [comment] 2021-01-27 14:03
Well it supports v4l, do you have the device, nothing more should be needed, it should just work like any other v4l capture device, do u have any issues?

**Comment by Foamier** [comment] 2021-01-27 20:36
I did get another of these modules, so now need to test if it works on RPi4 2GB with Hyperbian.

The USB devices (standard analogue video capture and HDMI USB grabber as mentioned above) that I used before had a lot more delay, adding to the visible delay between the TV screen and the LED reaction. The module that plugs directly into the camera connector of the RPi is about twice as expensive as a USB solution.
One advantage that analogue video capture cards have is that they already downscale the video, so less work to do for the CPU?

Will take some time to set this up and test. Hardest part will be the config entries for the module in Hyperbian.
Perhaps this weekend I'll have some time to spare. My LED strips 2812B 60/m LEDs have also arrived. Will be a nice upgrade from old WS2801 30/m LED strips, which have been running for the last 5 years or so.

**Comment by Foamier** [comment] 2021-02-14 15:11
So I installed the latest Hyperbian on a RPI4 2GB this weekend. Strip of WS2812B and level shifter on GPIO18 works well.

Still had a HDMI USB capture stick from the pikvm project, so tried that first.
(this device seems to be the same as the above mentioned from here:
[https://nl.aliexpress.com/item/4000917130635.html](https://nl.aliexpress.com/item/4000917130635.html))

Setup:
Source @ 1080p50 --5 port HDMI switch -- 4k HDMI splitter -- USB HDMI capture stick -- RPi4

When using a USB HDMI grabber it works practically out of the box with the latest Hyperbian. There is however a noticeable delay between the video on the TV and the reaction by the LEDs on the wall.
Live video preview on the hyperbian site also works well.

After replacing the USB stick with the tc358743 module, a few adjustments were required to get the module recognized.
Add dtoverlay=tc358743 to /boot/config/txt
Add cma=96M to /boot/cmdline.txt

A lot of the troubleshooting can be found here:
[https://www.raspberrypi.org/forums/viewtopic.php?t=120702&start=600](https://www.raspberrypi.org/forums/viewtopic.php?t=120702&start=600)

Some issues still exist.
1. The video resolution does not automatically set with v4l. This needs to be done manually. Not an issue for me but could be if the resolution changes when switching to a different source.
2. There is limited bandwidth on the CSI2 bus. It will not support 1080p50 as this exceeds the bandwidth. Solution for me will be replacing the splitter with a different splitter that down-scales the resolution on one port. This will make switching to 4k sources easier as well.
3. After selecting customer video source of /dev/video0 or unicam-image the following error shows up in the debug logs:

` 2021-02-14T14:44:45.420Z [hyperiond HYPERION] (DEBUG) (PriorityMuxer.cpp:161:registerInput()) Register new input 'System/V4L' with priority 240 as inactive

 2021-02-14T14:44:45.420Z [hyperiond COMPONENTREG] (DEBUG) (ComponentRegister.cpp:36:setNewComponentState()) V4L capture device: enabled

 2021-02-14T14:44:45.665Z [hyperiond V4L2:/DEV/VIDEO0] (INFO) configured v4l device: /dev/video0
 2021-02-14T14:44:45.687Z [hyperiond V4L2:/DEV/VIDEO0] (DEBUG) (V4L2Grabber.cpp:696:init_device()) Set resolution to width=1280 height=720
 2021-02-14T14:44:45.688Z [hyperiond V4L2:/DEV/VIDEO0] (ERROR) Throws error: Only pixel formats UYVY, YUYV, RGB32 and MJPEG are supported
 2021-02-14T14:44:45.690Z [hyperiond V4L2:/DEV/VIDEO0] (ERROR) Throws error nr: VIDIOC_STREAMON error code 22, Invalid argument
 2021-02-14T14:44:45.691Z [hyperiond V4L2:/DEV/VIDEO0] (INFO) Started
 2021-02-14T14:44:45.692Z [hyperiond V4L2:/dev/video0] (DEBUG) (GrabberWrapper.cpp:48:start()) Grabber start()
 2021-02-14T14:44:45.721Z [hyperiond V4L2:/DEV/VIDEO0] (ERROR) Throws error nr: VIDIOC_DQBUF error code 16, Device or resource busy
 2021-02-14T14:44:45.723Z [hyperiond V4L2:/DEV/VIDEO0] (ERROR) VIDIOC_STREAMOFF  error code  16, Device or resource busy
 2021-02-14T14:44:45.747Z [hyperiond V4L2:/DEV/VIDEO0] (INFO) Stopped
`
Logically live video on the Hyperbian page does also not work.

Looks like there is a format mismatch between hyperion and what the video driver/module can supply or the device is busy??
I'll try to capture the video with yavta or ustreamer when I have some more time.

**Comment by Lord-Grey** [comment] 2021-02-14 16:39
@Foamier we are currently working on a feature that the user can select from the options a grabber presents.
That hopefully will help to avoid misconfigurations going forward...

Interim state you can find in the following PR
https://github.com/hyperion-project/hyperion.ng/pull/1119

**Comment by samuele2723** [comment] 2021-03-22 10:30
Hello everyone, i am followi this because i want as well a 0 delay setup (currently i have a usb grabber stick that works out of the box).

Perhaps is there any more powerful usb grabber card available to get a 0 delay ambilight from hyperion?

**Comment by Kingo64** [comment] 2021-04-26 05:20
Hi @samuele2723, just writing to say that I've currently got a <50ms response time USB HDMI setup, I haven't measured it but it could potentially be around 20ms or so which is decently quick.

What you are looking for is a "HDMI to USB Video Capture Card" that specifically supports MJPEG. MJPEG is important since I've found YUV outputs to be around 500ms+ latency. Looks like the one I am using is the same as @Foamier. I've found that the latency goes down on MJPEG the lower you set the resolution as the tiny chip on the capture card doesn't need to work as hard - 720x480 60fps MJPEG is ideal.

I'm currently using a HDMI splitter/scaler (mixed mode) to send the original signal to my TV from my PC and the slave port on the splitter goes to the RPi4 w/ USB HDMI capture card.

[My Hyperion settings](https://i.imgur.com/7PcwcWs.png)
[Example eBay listing](https://www.ebay.com.au/itm/164812946302)
[Picture of what the grabber looks like](https://i.imgur.com/XYlEaXD.jpg)

**Comment by samuele2723** [comment] 2021-04-26 05:51
Hey there! Thanks for the reply. I think i already got your card and i am happy with the delay. I am running 16x9 custom pixel res. Lower is the better not sure if i get a gain from 480p to 9p but seems fine to me.

About grabber and scaler i have same setup with Ezcoo but i can't see dolby vision with that. Wonder if there is a dolby vision scaler working ![image](https://user-images.githubusercontent.com/66970905/116034768-25707700-a664-11eb-896b-c254e77ffc8f.jpeg)

![image](https://user-images.githubusercontent.com/66970905/116034784-299c9480-a664-11eb-8584-97cba31c3dac.jpeg)

**Comment by Lord-Grey** [comment] 2021-07-18 15:22
Can you re-test with alpha10 and report back please, if the issue is still present?

**Comment by Lord-Grey** [comment] 2021-08-01 13:47
Closing, as no feedback provided. Can be reopened, if needed.

**Closed by Lord-Grey** 2021-08-01 13:47 UTC
Labels: New Feature Request
