### ISSUE TITLE
Need to start USB grabber after starting Hyperion 

### ISSUE THREAD

**Issue by Iridahonda** [hyperion-project/hyperion.ng#491] opened 2017-12-23 07:01 UTC
With Raspberian on a RPi3 and 428 APA102 LEDS with UTV007 it seems the USB grabber shuts down during initialisation and must be restarted through the remote control function. 
I can post logs etc if needed.

**Comment by brindosch** [comment] 2018-01-08 13:39
Hello @Iridahonda 
thank you for your notice. I found the issue. Will be resolved soon.

brindosch

**Comment by giovanne123** [comment] 2018-02-27 06:35
Can confirm the behaviour. 
@brindosch, can you post the needed mods for resolving. I will test it...

P.s. my USB Cam / Grabber also after a while stops working ([hyperiond V4L2:/dev/video0] <INFO> Stopped), isnt restartable from webgui, ng restart and than start again from webgui is necessary. Dont know if related..?

**Comment by anktababa** [comment] 2018-05-07 12:59
Hello,
@brindosch : Is it already committed in a specific branch ? Do you need something on our side ?
Same thing here, in main branch, after few minutes the grabber is not working anymore (UTV007) but if i turn it off and on using the remote control it works again for few minutes.
Unfortunately i don't have any logs to share as even in debug mode there is no log related to this.

I tried also the rework branch, there is no issue about grabber turning off but it is not working and i have the following log messages (in warning level) : 
[hyperiond QTGRABBER] (ERROR) No displays found to capture from!
[hyperiond QTGRABBER] (ERROR) No displays found to capture from!

I will try with STK1160 grabber if it is the same thing.

**Comment by derstrassi** [comment] 2018-12-17 15:41
Hi, any news on this? 
I already tried the "rework" branch (which has it's own quirks) from @brindosch. This branch seems to have a fix for this issue but I was not able to find the right code parts.

**Comment by 9mateusz** [comment] 2019-01-17 22:52
Do we have any other branch where it is solved? the issue is realy annoying.
@derstrassi how you were able to test the branch? I tried to set up  and run but got lot of errors 'no schema definition'

**Comment by penfold42** [comment] 2019-01-18 00:39
Have you tried #523 ?
I think that has lots of bits from the rework branch

**Comment by 9mateusz** [comment] 2019-01-21 21:10
Thanks for help. Seems that branch you mentioned is affected by other issue at present. 
Maybe do you know any other branch where it is fixed? 
Before SD card in my RPI crashed I have checkout some branch where everything needed for me worked perfectly but I do not remember what it was. (not master)

**Comment by ssirkakriss** [comment] 2019-02-10 17:56
I've been running .NG for a wile with good results, from a build pulled from late Nov. 2018.  It has small bug of not starting the usb grabber, same a the OP.  Anyway I noticed some momentum on the project, So I pulled the latest master (as of this writing).

From a short test. It's working but still has the bug where the usb grabber in not enabled upon startup. And a new error (new to me) where the log is being spammed every few seconds with “[hyperiond QTGRABBER] (ERROR) No displays found to capture from!”

Currently running on Ubuntu 18.04,  X86 Atom 330/4mb, UTV007 usb grabber, 244 apa102 using udpraw with a lilon/wemos mini 1mb w/Scilor's esp2688 code. Built with “cmake -DCMAKE_BUILD_TYPE=Release ..” option.

Jut a small report of a short test from a avid Hyperion user.

Many thanks.

**Comment by Paulchen-Panther** [comment] 2019-02-10 18:53
which graphics system is running?

**Comment by Paulchen-Panther** [comment] 2019-02-10 19:02
You can exclude the QT Grabber from Hyperion with "cmake -DENABLE_QT=OFF -DCMAKE_BUILD_TYPE=Release .."

**Comment by Paulchen-Panther** [comment] 2019-02-10 19:04
Or disable the Platform capture in WebUI.

**Comment by ssirkakriss** [comment] 2019-02-11 03:23
I did disable Platform capture. Snip from my config.
`    "instCapture": {
        "systemEnable": false,
        "systemPriority": 250,
        "v4lEnable": true,
        "v4lPriority": 240
    },`

Compiling with "cmake -DENABLE_QT=OFF -DCMAKE_BUILD_TYPE=Release .." is throwing a error on my system running Ubuntu 18.04, X86 Atom 330. Snip from compile error https://pastebin.com/7BLD76PG .

**Comment by Paulchen-Panther** [comment] 2019-02-11 17:11
Please compile again with this [CMakeList.txt](https://gist.github.com/Paulchen-Panther/a367b394c77bb008cfb448270e959cec) file. Copy the file in /src/hyperiond folder and overwrite the exist file.

**Comment by ssirkakriss** [comment] 2019-02-11 18:16
Ok. I've replaced CMakeList.txt, still some errors. https://pastebin.com/2J0a7sfb

**Comment by Paulchen-Panther** [comment] 2019-02-11 18:50
then replace the line in the CMakeList.txt like this:

original line: target_link_libraries (hyperiond Qt5 :: Core Qt5 :: Gui Qt5 :: Network Qt5 :: Widgets)
replace with: target_link_libraries (hyperiond Qt5 :: Widgets)

**Comment by ssirkakriss** [comment] 2019-02-11 19:20
Ok, replaced the line. New errors however. https://pastebin.com/eTTZAFzz

**Comment by Paulchen-Panther** [comment] 2019-02-11 19:28
I do not understand that. You wrote, he compiled at the beginning but in the end reported that hyperiond can not be linked with QWidget.
Now he does not find the hyperiond.h file when configuring before compiling?
Can you load hyperion.ng again and paste the two lines difference in the file CMakeList.txt?

**Comment by ssirkakriss** [comment] 2019-02-11 20:52
Ok I refreshed the Hyperion build Dir. 
This is a complete output from  "cmake -DENABLE_QT=OFF -DCMAKE_BUILD_TYPE=Release .." and "make -j $(nproc)" using the original CMakeList.txt.

Output: https://pastebin.com/nYga6Aa7

Using the the first edit of CMakeList.txt ( [here](https://gist.github.com/Paulchen-Panther/a367b394c77bb008cfb448270e959cec) )
I changed line number 63 from 
"target_link_libraries(hyperiond Qt5::Core Qt5::Gui Qt5::Network Qt5::Widgets)" 
To 
"target_link_libraries(hyperiond Qt5::Widgets)" 

The output is the same as the previous posted errors.

I'm just a hobbyist,  I hope this is being helpful, and make sense.

**Comment by Paulchen-Panther** [comment] 2019-02-11 21:42
https://pastebin.com/UScQyuuz

**Comment by Paulchen-Panther** [comment] 2019-02-11 22:03
Or clone my repository:

```
git clone --recursive https://github.com/Paulchen-Panther/hyperion.ng.git NGrework
cd ssirkakriss
git checkout ssirkakriss
mkdir build
cd build
cmake -DENABLE_QT=OFF -DCMAKE_BUILD_TYPE=Release ..
make -j $(nproc)
```

**Comment by ssirkakriss** [comment] 2019-02-11 22:03
It seems my dyslexia has the better of me today. Carefully rereading I see my mistake. 

I did not modify the correct CMakeLists.txt.

Recompiling now.

Very sorry for my errors and noobishness/confusion

**Comment by ssirkakriss** [comment] 2019-02-11 22:32
Ok. compile done and Hyperion is working.
 Hyperion now starts with the USB grabber as active and the log is error free.

Looks good.

Again, I apologize for my errors/confusion.

Many thanks.

**Comment by Paulchen-Panther** [comment] 2019-02-12 21:37
@iridahonda can this bei closed?

**Comment by Iridahonda** [comment] 2019-02-12 21:39
Hi

Sure


/T.


On Feb 12, 2019 at 10:37 pm, <Paulchen Panther<mailto:notifications@github.com>> wrote:


@Iridahonda<https://clicktime.symantec.com/32KHtBjLKkZnynzb9Fz5DVF6H2?u=https%3A%2F%2Fgithub.com%2FIridahonda> can this bei closed?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://clicktime.symantec.com/38bLd2KipEodt9DEzjwerTw6H2?u=https%3A%2F%2Fgithub.com%2Fhyperion-project%2Fhyperion.ng%2Fissues%2F491%23issuecomment-462945694>, or mute the thread<https://clicktime.symantec.com/3C9FRcH9tZ1SE9S4vvLsHgM6H2?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAhLPsv4XtFy8Z0dW4ASQI0s9qhirWJeFks5vMzQTgaJpZM4RLmKS>.

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to which they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Closed** 2019-02-12 22:50 UTC
Labels: Backlog
