### ISSUE TITLE
USB HDMI Grabber not showing up in live view

### ISSUE THREAD

**Issue by wuast94** [hyperion-project/hyperion.ng#1083] opened 2020-11-07 17:18 UTC
- [x] I confirm that this is an issue rather than a question.

## Bug report

I have bought an hdmi usb grabber, googled arround and didnt find a solution, but some people just pluged it in and it works:
https://www.amazon.de/gp/product/B0895N9KM5/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1

#### What is actually happening?
Nothing, played arround with the usb capture settings, changed Devices and other settings but i just see an black image 

#### System

Hyperion Server: 
- Build:       (HEAD detached at 08909b8a) (Paulchen-Panther-75963ca9/08909b8a-1600115237)
- Build time:  Sep 14 2020 21:05:54
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.8
- UI Lang:     auto (BrowserLang: en-US)
- UI Access:   default
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: HyperBian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (5.4.51-v7+ (WS: 32))
- Browser:      Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0 

#### Extras ####

dont know if its helpfull but the output from v4l2-ctl --all
```
pi@HyperBian:~ $ v4l2-ctl --all
Driver Info:
	Driver name      : uvcvideo
	Card type        : USB Video: USB Video
	Bus info         : usb-3f980000.usb-1.3
	Driver version   : 5.4.51
	Capabilities     : 0x84a00001
		Video Capture
		Metadata Capture
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps      : 0x04200001
		Video Capture
		Streaming
		Extended Pix Format
Media Driver Info:
	Driver name      : uvcvideo
	Model            : USB Video: USB Video
	Serial           : 
	Bus info         : usb-3f980000.usb-1.3
	Media version    : 5.4.51
	Hardware revision: 0x00002100 (8448)
	Driver version   : 5.4.51
Interface Info:
	ID               : 0x03000002
	Type             : V4L Video
Entity Info:
	ID               : 0x00000001 (1)
	Name             : USB Video: USB Video
	Function         : V4L2 I/O
	Flags         : default
	Pad 0x01000007   : 0: Sink
	  Link 0x0200000d: from remote pad 0x100000a of entity 'Processing 2': Data, Enabled, Immutable
Priority: 2
Video input : 0 (Camera 1: ok)
Format Video Capture:
	Width/Height      : 1920/1080
	Pixel Format      : 'MJPG' (Motion-JPEG)
	Field             : None
	Bytes per Line    : 0
	Size Image        : 4147200
	Colorspace        : sRGB
	Transfer Function : Default (maps to sRGB)
	YCbCr/HSV Encoding: Default (maps to ITU-R 601)
	Quantization      : Default (maps to Full Range)
	Flags             : 
Crop Capability Video Capture:
	Bounds      : Left 0, Top 0, Width 1920, Height 1080
	Default     : Left 0, Top 0, Width 1920, Height 1080
	Pixel Aspect: 1/1
Selection: crop_default, Left 0, Top 0, Width 1920, Height 1080, Flags: 
Selection: crop_bounds, Left 0, Top 0, Width 1920, Height 1080, Flags: 
Streaming Parameters Video Capture:
	Capabilities     : timeperframe
	Frames per second: 30.000 (30/1)
	Read buffers     : 0
                     brightness 0x00980900 (int)    : min=-128 max=127 step=1 default=-11 value=-11
                       contrast 0x00980901 (int)    : min=0 max=255 step=1 default=148 value=148
                     saturation 0x00980902 (int)    : min=0 max=255 step=1 default=180 value=180
                            hue 0x00980903 (int)    : min=-128 max=127 step=1 default=0 value=0
```

**Comment by Paulchen-Panther** [comment] 2020-12-13 10:34
I am closing this issue because there are no steps to reproduce it.
HDMI grabber tested successfully on HyperBian RPi3 B +.
Proof:
![remote](https://user-images.githubusercontent.com/16664240/102009326-02899a00-3d37-11eb-965c-2d4ab63a32ff.png)
![about](https://user-images.githubusercontent.com/16664240/102009327-04ebf400-3d37-11eb-80c9-79f94cdeb69e.png)

"v4l2-ctl --all" output:
```
pi@HyperBian:~ $ v4l2-ctl --all
Driver Info:
        Driver name      : uvcvideo
        Card type        : FHD Capture: FHD Capture
        Bus info         : usb-3f980000.usb-1.5
        Driver version   : 5.4.72
        Capabilities     : 0x84a00001
                Video Capture
                Metadata Capture
                Streaming
                Extended Pix Format
                Device Capabilities
        Device Caps      : 0x04200001
                Video Capture
                Streaming
                Extended Pix Format
Media Driver Info:
        Driver name      : uvcvideo
        Model            : FHD Capture: FHD Capture
        Serial           :
        Bus info         : usb-3f980000.usb-1.5
        Media version    : 5.4.72
        Hardware revision: 0x00000100 (256)
        Driver version   : 5.4.72
Interface Info:
        ID               : 0x03000002
        Type             : V4L Video
Entity Info:
        ID               : 0x00000001 (1)
        Name             : FHD Capture: FHD Capture
        Function         : V4L2 I/O
        Flags         : default
        Pad 0x01000007   : 0: Sink
          Link 0x02000013: from remote pad 0x100000a of entity 'Extension 4': Data, Enabled, Immutable
Priority: 2
Video input : 0 (Camera 1: ok)
Format Video Capture:
        Width/Height      : 640/480
        Pixel Format      : 'MJPG' (Motion-JPEG)
        Field             : None
        Bytes per Line    : 0
        Size Image        : 614400
        Colorspace        : sRGB
        Transfer Function : Default (maps to sRGB)
        YCbCr/HSV Encoding: Default (maps to ITU-R 601)
        Quantization      : Default (maps to Full Range)
        Flags             :
Crop Capability Video Capture:
        Bounds      : Left 0, Top 0, Width 640, Height 480
        Default     : Left 0, Top 0, Width 640, Height 480
        Pixel Aspect: 1/1
Selection: crop_default, Left 0, Top 0, Width 640, Height 480, Flags:
Selection: crop_bounds, Left 0, Top 0, Width 640, Height 480, Flags:
Streaming Parameters Video Capture:
        Capabilities     : timeperframe
        Frames per second: 30.000 (30/1)
        Read buffers     : 0
                     brightness 0x00980900 (int)    : min=0 max=255 step=1 default=128 value=128
                       contrast 0x00980901 (int)    : min=0 max=255 step=1 default=128 value=128
                     saturation 0x00980902 (int)    : min=0 max=255 step=1 default=128 value=128
                            hue 0x00980903 (int)    : min=-32 max=31 step=1 default=0 value=0
```

**Closed by Paulchen-Panther** 2020-12-13 10:34 UTC
Labels: Waiting For Review
