### ISSUE TITLE
USB capture in YUYV format result in 100% cpu load 

### ISSUE THREAD

**Issue by happyme531** [hyperion-project/hyperion.ng#908] opened 2020-07-26 11:35 UTC
- [x] I confirm that this is an issue rather than a question.

## Bug report
When enabling USB capture, sometimes hyperion will capture in YUYV pixel format, and then the cpu load reachs 100%.
In other times, MJPEG is used, and the system behaves normally.

#### Steps to reproduce
Plug in a capture device which supports both YUYV and MJPEG format, enable USB capture, see the cpu load.
note: I'm not sure how the hyperion choose the pixel format(random?), and it may vary after reboot.

#### What is expected?
Hyperion chooses the best pixel format and cpu load stays reasonable.
Or I can choose the best pixel format manually in the web config interface.

#### What is actually happening?
Hyperion choose the pixel format in an weird way (actrually no-change ?), and cause the system to lag.

#### System

Hyperion Server: 
- Build:       (HEAD detached at ffa2fd45) (Paulchen-Panther-69e9fa6d/ffa2fd45-1595517126) 
- Build time:  Jul 24 2020 16:01:54 
- Git Remote:  https://github.com/hyperion-project/hyperion.ng 
- Version:     2.0.0-alpha.7 
- UI Lang:     en (BrowserLang: zh-CN) 
- UI Access:   expert - Avail Capt:  v4l2,framebuffer,amlogic,qt  
Hyperion Server OS:  
- Distribution: Ubuntu 18.04.4 LTS 
- Arch:         arm64 
- Kernel:       linux (5.4.43-sunxi64 (WS: 64))
- Browser:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

note: The board is Orange pi win plus, soc is allwinner a64, 2GB ram.

**Comment by Paulchen-Panther** [comment] 2020-08-02 07:29
Which USB grabber is used?

**Comment by happyme531** [comment] 2020-08-02 10:42
this-> https://b2b.baidu.com/land?url=https%3A%2F%2Fwww.china.cn%2Fshipincaijiqia%2F4643549440.html%3Fbdb2b8a2d%3D3608689166240111835&query=hdmi%E9%87%87%E9%9B%86%E5%8D%A1&category=3C%E7%94%B5%E5%AD%90%3B%E6%95%B0%E7%A0%81%E9%85%8D%E4%BB%B6%3B%E8%A7%86%E9%A2%91%E9%87%87%E9%9B%86%E5%8D%A1

and it based on MS2109 chip.

**Comment by Lord-Grey** [comment] 2021-07-18 16:45
Can you re-test with alpha10 and report back please, if the issue is still present?

**Comment by Lord-Grey** [comment] 2021-08-01 13:46
Closing, as no feedback provided. Can be reopened, if needed.

**Closed by Lord-Grey** 2021-08-01 13:46 UTC
Labels: Waiting For Review
