### ISSUE TITLE
[Feature request] Don't constantly send colors via serial port

### ISSUE THREAD

**Issue by philibertc** [hyperion-project/hyperion.ng#1294] opened 2021-08-01 10:41 UTC
#### What problem does this feature solve?
Higher CPU consumption.

#### How should this be implemented in your opinion?
Sending information only when needed.

#### Are you willing to work on this yourself?
No.

**Comment by Lord-Grey** [comment] 2021-08-01 13:22
@philibertc Would you mind outlining your problem in a more detailed fashion, please?
This might just because of misconfiguration on your end.

Given that some serial devices need a continuous feed a serial device has teh configuration item of "Rewrite Time".
This means that after the given timeframe no update happend a rewrite of the previous color is done.
In case your device maintains a stable state itself, just set Rewrite Time to zero.
I know that in the past a device switch off was simulated by writing frequent black, but I removed that behaviour already some releases back.

To be fair, I lately identified that in Smoothing there is a "Continuous Output" flag which might result in a similar effect.
So disable either smoothing or continuous output.

In case there is still constantly color streaming after you fixed your configuration, happy to hear in which cases it occurs that we can address it.

**Comment by Lord-Grey** [comment] 2021-08-01 19:32
@philibertc To address the continuous update problem space in regard to smoothing, see PR #1295 1295.
Please check, if that PR addresses your issue raised.

**Comment by philibertc** [comment] 2021-08-02 08:03
Hello,
By putting latch time to 0 it still constantly sends colors.
I set it to 0.5 s and now the colors are updated every 500 ms when there is no change.
I don't know what the Refresh Time parameter (set to 1000ms by default) changes, I tried setting it to 0 but it doesn't change anything apparent.
So this feature already exists, sorry.

**Comment by philibertc** [comment] 2021-08-02 08:14
Hello, @Lord-Grey 
I only found Refresh Time and Latch Time (in expert mode) but setting Refresh Time to 0 does not solve the problem...

**Comment by Lord-Grey** [comment] 2021-08-02 14:57
Hi @philibertc As mentioned above, it might be caused by Smoothing.
Would you mind to disable Smoothing for testing purposes? Do updates still happen?

In case you would like to try, I already did some updates to smoothing to pause when no source is available: see #1295

**Comment by philibertc** [comment] 2021-08-02 15:00
> Would you mind to disable Smoothing for testing purposes?
Yes, but I never managed to compile Hyperion, so I'm not able to install #1295

**Comment by tpmodding** [comment] 2021-08-02 15:02
https://github.com/hyperion-project/hyperion.ng/actions/runs/1087985725

you can download down below at "Artifacts" the packages you need

**Comment by philibertc** [comment] 2021-08-02 15:06
Thanks, I'm gonna try to install that.

**Comment by Lord-Grey** [comment] 2021-08-12 16:29
@philibertc Any update?

**Comment by Lord-Grey** [comment] 2021-09-01 06:02
Closing, as no feedback provided. Can be reopened, if needed.

**Closed by Lord-Grey** 2021-09-01 06:02 UTC
Labels: Waiting for Input
