### ISSUE TITLE
No control from HA once source is inactive

### ISSUE THREAD

**Issue by Coolie1101** [hyperion-project/hyperion.ng#1449] opened 2022-03-28 08:44 UTC
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
Try turning on from Home Assistant after source has been marked as "inactive"

**"Log Output after turning OFF USB Source"**
```
2022-03-27T17:25:08.728Z [ V4L2] (INFO) Signal lost
2022-03-27T17:25:09.739Z [ HYPERION] (DEBUG) (PriorityMuxer.cpp:271:setInputImage()) Priority 240 is now inactive
2022-03-27T17:25:09.742Z [ HYPERION] (DEBUG) (PriorityMuxer.cpp:374:setCurrentTime()) Set visible priority to 255
2022-03-27T17:25:09.743Z [ HYPERION] (DEBUG) (Hyperion.cpp:571:handleSourceAvailability()) priority[255], previousPriority[240]
2022-03-27T17:25:09.744Z [ HYPERION] (DEBUG) (Hyperion.cpp:574:handleSourceAvailability()) No source left -> Pause output processing and switch LED-Device off
```

#### What is expected?
LED's should turn on and allow for selecting various effect's.

#### What is actually happening?
Nothing, I can only control via Home Assistant if the source is active, or if I turn the LED's on via the Hyperion Free App.

#### System
Hyperion Server: 
- Build:           (HEAD detached at 2.0.12) (GitHub-dc6aa4d/df14958-1637501177)
- Build time:      Nov 21 2021 17:25:08
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.12
- UI Lang:         auto (BrowserLang: en-US)
- UI Access:       expert
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Config path:     /root/.hyperion
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 4 (v7l)
- CPU Type:       Raspberry Pi Zero 2 W Rev 1.0
- CPU Revision:   902120
- CPU Hardware:   BCM2835
- Kernel:         linux (5.10.103-v7+ (WS: 32))
- Root/Admin:     true
- Qt Version:     5.11.3
- Python Version: 3.7.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36

**Comment by Lord-Grey** [comment] 2022-03-30 19:18
I would assume that this an HA Problem that it does think the LEDs are not ready…
That Hyperion works with the App is an indication that the issue is not related to Hyperion as it handles the App requests correctly.
You might want testing with the Hyperion nightly build, in case updates were done HA is relying on.
I will close this for now.

**Closed by Lord-Grey** 2022-03-30 19:18 UTC
Labels: No-Hyperion Issue
