### ISSUE TITLE
Background Color not beeing displayed at startup 

### ISSUE THREAD

**Issue by TheAndi** [hyperion-project/hyperion.ng#745] opened 2020-03-27 11:56 UTC
On both my instances (WS281x, udpraw) my background color does not show up.

But when I set a start effect **and** enable continuous output, then the start color shows.

I think the background should be displayed even if no start effect is set or no continuous output is enabled.

Furthermore:
![grafik](https://user-images.githubusercontent.com/33332336/77753087-16666200-7029-11ea-8944-f1e9eec0e3d2.png)

If I close my web color or set System as active, the color does not change back to the system/background color (still having continuous output enabled).

Also (might be a different issue), turning the Led Device off sets the LEDs to off, but turning it on again does not show the active source. Only when I reselect a color the output enables. (still having continuous output enabled).

#### System
Raspberry Pi 1 B+, Raspbian Buster Lite, Hyperion.ng alpha3

**Comment by Nears** [comment] 2020-04-20 08:32
I do see a similar issue.

- If I have hyperion.ng running with internal grabber only and i deactivate the LED Hardware the the LEDs go off. If I reactivate the LED Hardware the LEDs are active again and show the right colors depending on the picture sown.
- If I have hyperion.ng running with internal grabber but overwrite this with a color at low priotity value via the "remote" in the webinterface the color is shown. If i deactivate the LED Hardware the LEDs go off. If I reactivate the LED Hardware **the LED stay off**. The only way to get the LEDs active is neither change the color to a different color code or remove the Color from the priority list via the "x". Doing this I will see the LEDs based on the internal grabber again.

System: RPI4, Buster, hyperion.ng alpha 5

**Comment by Lord-Grey** [comment] 2021-07-18 17:05
Can you re-test with alpha10 and report back please, if the issue is still present?

**Comment by Lord-Grey** [comment] 2021-08-04 19:33
Closing, as no feedback provided. Can be reopened, if needed.

**Closed by Lord-Grey** 2021-08-04 19:33 UTC
Labels: Bug, needs investigation
