### ISSUE TITLE
hyperion web interface issues

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#323] opened 2016-12-09 13:05 UTC
1) fails on IE 11
dark background with pretty HYPERION logo in front of:
  /\
/ ! \
-----
ERROR
general_btn_ok

2) with firefox it needs to default to English on first launch

**Comment by brindosch** [comment] 2016-12-09 13:19
Congrats for your first visit :)
> fails on IE 11

It never worked before :) This needs a bunch of debug and work arounds
> with firefox it needs to default to English on first launch

It should be, but never tested another browser locale. I will implement a debug mode for the webui to enable logging of such stuff.

**Comment by brindosch** [comment] 2016-12-09 13:43
You saw on FF just the tokens and no language right?

**Comment by penfold42** [comment] 2016-12-09 13:49
Yep

**Comment by brindosch** [comment] 2016-12-09 16:43
I could confirm your issue, it is a weird result of a missing fallback pathbuild/load for en-US.
```
Loading messages from: i18n/en-US.json 
Loading messages from: i18n/en.json  
Trying fallback locale for en-US: en
Error in loading messages from i18n/en-US.json Exception: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```
Parse error is a missing file, but won't bother as it works as intended.

https://github.com/hyperion-project/hyperion.ng/commit/9f6edc02968760530ec187acb421a5dbb5f534ab

Have fun

**Comment by brindosch** [comment] 2016-12-09 21:43
So the internet explorer 11 throws following error
`SCRIPT12008: WebSocket Error: Incorrect HTTP response. Status code 200, OK`

Is our response 100% conform?
@redPanther

**Comment by redPanther** [comment] 2016-12-09 21:52
don't know. I can't test with IE I have no  windows here, also no windows at work ... for bussniss I do web dev for internal purpose only for ff/chrome ....

**Comment by brindosch** [comment] 2016-12-21 23:38
I tried again logging a little bit and reading instructions for websocket, also the paper.
I have no idea why ie11 talks about a invalid response
This is the websocket output, which is a wrong HTTP reponse? Do i need to sniff the connections for more infoormations?
`[object WebSocket]{binaryType: "blob", bufferedAmount: 0, CLOSED: 3, CLOSING: 2, CONNECTING: 0, extensions: "", onclose: null, onerror: null, onmessage: null, onopen: null, OPEN: 1, protocol: "", readyState: 0, url: "ws://192.16..."}`

Also pointing to https://msdn.microsoft.com/de-de/library/hh673567(v=vs.85).aspx
doesn't give me a hint.

**Comment by redPanther** [comment] 2016-12-23 08:03
Perhaps we should give up our own ws implemention and use e.g. https://libwebsockets.org/

**Comment by brindosch** [comment] 2016-12-23 10:31
Well the other question is. Is IE11 compatible? I think i used some code which is not. But the websocket error instead a proper message is not so nice. Also i don't know how other browsers behave (not Chrome FF) on Smartphones, Tablets all in between. A list what is NOT working would be good to make a better decision (But for this you need more persons for testing)

**Comment by penfold42** [comment] 2016-12-23 10:44
Will get around the scale limit I think I seeing ?
My 750 led instance just tries errors (someone sending big stuff) but my 24 and 80 led instances are  fine

**Comment by brindosch** [comment] 2016-12-23 11:03
I really wonder, even the default config fails on my Pis.
What is working fine: Running Hyperion on Ubuntu 16.04(64bit) and connect within the same machine. But when i try to save this instance from Windows 7 (64bit) it fails for 100% (default conf) like my Pis.
Maybe it's no 32bit vs 64bit issue? (Due to the point i can't save any instance from smartphone/tablet)

Just strange

**Comment by penfold42** [comment] 2016-12-23 12:08
How hard is it to use an off the shelf as library ?

A bit of pain now might be much less pain in the longer run

**Comment by b1rdhous3** [comment] 2016-12-23 14:43
I am facing excact the same problems like @brindosch

**Comment by redPanther** [comment] 2016-12-23 18:24
perhapswe should use plain old http post from webserver to save the config. Perhaps transfering big thinks via websockests is a bad idea

**Comment by redPanther** [comment] 2016-12-23 18:36
I tested from my android phone with firefox. Ui looks usable. Saving doesn't work. The methode (/hack) to convert json request to utf8 didn't work. As I wrote before, we should switch to http transfer for config save/load. Other thing is we should implement a "keep alive" json message. Current methode to use "serverinfo" as keep alive doesn't work well - there is to much data to send and this can lead to timeout and ui detects a connection lost.

Other thing is, would we good if we can hide(collaps) help/intro texts on small screens.

**Comment by brindosch** [comment] 2016-12-23 20:23
> if we can hide(collaps) help/intro texts on small screens.

Is already on my list.
intro texts are already hidden (which pixel width do we talk?)

**Comment by redPanther** [comment] 2016-12-23 20:58
480x800

**Comment by brindosch** [comment] 2016-12-23 21:09
So sad, 767 is the break point :)
I could move it to a higher point :)

**Comment by redPanther** [comment] 2017-03-01 13:12
@penfold42 are your initial issue here solved in current version? If so please close, otherwise some words to current state would be cool. thx!

**Comment by brindosch** [comment] 2017-03-01 14:04
No, the Header is till not valid for IE11
WebSocket Error: Incorrect HTTP response. Status code 200, OK

But the results is now a lost connection loop which never shows the ui. (Which came with my "trigger LC when socket is closed")
I have no idea how to debug this properly. As the microsoft docu also doesn't tell me something new and dev mode of ie11 is also very tight in output infos.

Windows 10 Edge works fine.
The current market share of IE is 4%. So the problem will resolve itself over time... ;)
http://gs.statcounter.com/

**Comment by redPanther** [comment] 2017-03-01 14:27
edge is the new m$ browser? I don't have a clue about windows stuff. (it's nearly 17 years since I abandoned ms prodcts in my personal and bussiness life )

**Comment by brindosch** [comment] 2017-03-01 16:52
Yes :)
Regarding the spec: https://tools.ietf.org/html/rfc6455#section-4.2.2
I can't see a problem compared with chrome for websocket event output.

**Comment by redPanther** [comment] 2017-03-01 18:32
just saw in QT 5.9:
    Qt WebSockets
        Added support to handle external QTcpSocket
so in future we will replace our handmade solution with qt stuff

**Comment by brindosch** [comment] 2017-03-01 21:27
Weird. 2021 if you keep 4 years backward
:)

**Comment by redPanther** [comment] 2017-03-02 09:29
we won't fix this issue ....

**Closed by redPanther** 2017-03-02 09:29 UTC
Labels: Backlog, wontfix
