### ISSUE TITLE
Backlight threshold doesn't work

### ISSUE THREAD

**Issue by FrodoVDR** [hyperion-project/hyperion.ng#767] opened 2020-04-11 21:35 UTC
- [x] I confirm that this is an issue rather than a question.

## Bug report
Backlight threshold 0 all lights shine with 50 %, max was 98 % with minimum effect.

#### Steps to reproduce
Backlight threshold 0
LED stripe apa102 with 210 LEDs

#### What is expected?
All lights off if signal black and Backlight threshold 0

#### System
Hyperion Server: 
- Build:       master (GitHub-e6c0e97/060d9f4-1586506755)
- Build time:  Apr 11 2020 18:43:25
- Git Remote:  https://github.com/hyperion-project/hyperion.ng.git
- Version:     2.0.0-alpha.4
- UI Lang:     en (BrowserLang: de)
- UI Access:   default
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 9 (stretch)
- Arch:         arm
- Kernel:       linux (4.19.88-v7+ (WS: 32))
- Browser:      Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0

**Comment by Lord-Grey** [comment] 2021-08-04 19:31
Can you re-test with alpha10 and report back please, if the issue is still present?

**Comment by Lord-Grey** [comment] 2021-08-17 16:28
Closing, as no feedback provided. Can be reopened, if needed.

**Closed by Lord-Grey** 2021-08-17 16:28 UTC
Labels: Waiting for Input
