### ISSUE TITLE
Pi Blaster not working

### ISSUE THREAD

**Issue by JulianMined** [hyperion-project/hyperion.ng#715] opened 2020-03-06 19:35 UTC
I can use Pi-Blaster with terminal but not with Hyperion.

[hyperiond LEDDEVICE] <INFO> Connected to device(/dev/pi-blaster)
[hyperiond LEDDEVICE] <ERROR> Device disabled, device 'piblaster' signals error: 'Device (/dev/pi-blaster) is already open.'
[hyperiond LEDDEVICE] <ERROR> Device 'piblaster' cannot be enabled, as it is not ready!

**Comment by Lord-Grey** [comment] 2020-03-08 14:32
@JulianMined Do you have another hyperion instance still running?

Alternatively, which platform are you running on and would you be able to compile, if I provide you with a modified version?

**Comment by JulianMined** [comment] 2020-03-08 15:28
I tried to run it in a second instance on Raspbian Buster.
The first instance uses ws2812spi.

**Comment by Lord-Grey** [comment] 2020-03-08 15:31
Does it work, if you only run one instance with Pi-Blaster?

**Comment by JulianMined** [comment] 2020-03-15 15:23
@Lord-Grey No, that's also not working

**Comment by Lord-Grey** [comment] 2020-06-29 21:20
@JulianMined Could you check, if PR #855 addresses your issue?

**Comment by Lord-Grey** [comment] 2021-07-18 17:05
Can you re-test with alpha10 and report back please, if the issue is still present?

**Comment by Lord-Grey** [comment] 2021-08-01 13:45
Closing, as no feedback provided. Can be reopened, if needed.

**Closed by Lord-Grey** 2021-08-01 13:45 UTC
Labels: bug, needs investigation
