### ISSUE TITLE
WLED on macOS bug

### ISSUE THREAD

**Issue by Zarkstar** [hyperion-project/hyperion.ng#1104] opened 2020-12-02 03:18 UTC
- [x] I confirm that this is an issue rather than a question.

## Bug report
Hyperion with wled works as expected on windows, but on Mac it flashes the default WLED color every once in a while.<del>  I suppose this is due to home assistant trying to take control on the device, but I was expecting it to behave like in W10, where home assistant can't override WLED UDP unless stated. </del> EDIT: I've stopped home assistant and ran several test. The problem seems to be unrelated as it continues even after stopping home assistant. I guess there is something in Hyperion for MacOS that just pauses the connection with WLED, which return to its normal state after a while

#### Steps to reproduce
Configure instance with wled on Hyperion Mac. Run until the problem manifests

#### What is expected?
Hyperion grabber continuing to work as normal, as the same setup do on windows

#### What is actually happening?
WLED changes to a solid color and it takes a while to go back at normal activity and sometimes it just goes black. Console output after the error:

2020-12-02T15:52:18.951 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:251:setInputImage() | Priority 250 is now inactive
2020-12-02T15:52:18.951 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:351:setCurrentTime() | Set visible priority to 255
2020-12-02T15:52:18.952 hyperiond HYPERION     : <DEBUG> Hyperion.cpp:559:handlePriorityChangedLedDevice() | priority[255], previousPriority[250]
2020-12-02T15:52:18.952 hyperiond HYPERION     : <DEBUG> Hyperion.cpp:562:handlePriorityChangedLedDevice() | No source left -> switch LED-Device off
2020-12-02T15:52:18.958 hyperiond LEDDEVICE    : <DEBUG> ProviderRestApi.cpp:179:getResponse() | Previous line repeats 1 times
2020-12-02T15:52:18.959 hyperiond LEDDEVICE    : <DEBUG> LedDeviceWled.cpp:150:powerOff() | 
2020-12-02T15:52:18.959 hyperiond LEDDEVICE    : <DEBUG> ProviderRestApi.cpp:150:put() | PUT: [http://192.168.0.42/json/state] [{"on":false}]
2020-12-02T15:52:18.983 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:251:setInputImage() | Priority 250 is now active
2020-12-02T15:52:18.983 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:351:setCurrentTime() | Set visible priority to 250
2020-12-02T15:52:18.983 hyperiond HYPERION     : <DEBUG> Hyperion.cpp:559:handlePriorityChangedLedDevice() | priority[250], previousPriority[255]
2020-12-02T15:52:18.984 hyperiond HYPERION     : <DEBUG> Hyperion.cpp:569:handlePriorityChangedLedDevice() | new source available -> switch LED-Device on
2020-12-02T15:52:18.984 hyperiond LEDDEVICE    : <DEBUG> LedDeviceWled.cpp:132:powerOn() | 
2020-12-02T15:52:18.984 hyperiond LEDDEVICE    : <DEBUG> ProviderRestApi.cpp:150:put() | PUT: [http://192.168.0.42/json/state] [{"on":true}]
2020-12-02T15:52:19.094 hyperiond LEDDEVICE    : <DEBUG> ProviderRestApi.cpp:179:getResponse() | Reply.httpStatusCode [200]

#### System

Hyperion Server: 
- Build:           (HEAD detached at 83338dc3) (Paulchen Panther-ca50487e/83338dc3-1605733041)
- Build time:      Nov 18 2020 21:05:15
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.9
- UI Lang:         auto (BrowserLang: en-us)
- UI Access:       expert
- Avail Capt:      osx,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   macOS 10.16
- Architecture:   x86_64
- Kernel:         darwin (20.1.0 (WS: 64))
- Qt Version:     5.15.1
- Python Version: 3.9.0
- Browser:        Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15

**Comment by SmartHbdev** [comment] 2021-02-16 01:33
Same bug for me with latest alpha 9 i just have compiled. It works fine maybe 1 minute and colors no more match on a video test. A sort of lag. Colors just stay in previous state, no  more move, shut down some seconds and restart fine. All this in a loop of 1-2 minutes or less.

It works fine with windows 10.

My setup is:
Arduino nano baud rate 500000, Sk9822, macos big sur, 4k screen

Let me know if i can help with some logs (i don't know where to look).

**Comment by Lord-Grey** [comment] 2021-07-18 15:24
Can you re-test with alpha10 and report back please, if the issue is still present?

**Comment by Lord-Grey** [comment] 2021-08-04 18:46
Closing, as no feedback provided. Can be reopened, if needed.

**Closed by Lord-Grey** 2021-08-04 18:46 UTC
Labels: Waiting For Review

**Comment by Rushtones** [comment] 2023-03-13 14:11
Hey ich habe ein ähnliches Problem bei der Verbindung von Mac, Hyperion und wled. Hier kommt es ca. 2x in der Minute zum Signal Verlust. Unter Windows läuft es.
