### ISSUE TITLE
Grabber connecting/disconnecting all the time

### ISSUE THREAD

**Issue by btk999** [hyperion-project/hyperion.ng#794] opened 2020-05-10 09:13 UTC
- [x] I confirm that this is an issue rather than a question.

## Bug report
Hyperion.NG looses connection to USB Grabber. This causes LED will switch off and turn on again a few seconds later. See Debug logs below.
Hyperion Classic works fine on same system, so i guess this is not a hardware / wiring problem. 

#### Steps to reproduce
Start Hyperion.NG, 

#### What is expected?
Grabber connected all the time

#### What is actually happening?
Sun 10 May 2020 10:11:15 BST:  [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:238:setInputImage()> Priority 100 is now inactive
Sun 10 May 2020 10:11:16 BST:  [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:238:setInputImage()> Priority 100 is now active
Sun 10 May 2020 10:11:17 BST:  [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:238:setInputImage()> Priority 100 is now inactive
Sun 10 May 2020 10:12:22 BST:  [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:238:setInputImage()> Priority 100 is now active
Sun 10 May 2020 10:12:23 BST:  [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:238:setInputImage()> Priority 100 is now inactive
Sun 10 May 2020 10:12:24 BST:  [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:238:setInputImage()> Priority 100 is now active
Sun 10 May 2020 10:12:25 BST:  [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:238:setInputImage()> Priority 100 is now inactive
Sun 10 May 2020 10:12:27 BST:  [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:238:setInputImage()> Priority 100 is now active
Sun 10 May 2020 10:12:28 BST:  [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:238:setInputImage()> Priority 100 is now inactive

#### System
Raspberry PI Model 1B with latest Hyperion.NG alpha.
Setup 265 WS2812B LEDs on 65 inch TV, grabbing hdmi signal with feintech splitter, hdmi-to-AV and finally usbtvf007 grabber.

Hyperion Server: 
- Build:       (HEAD detached at e3587923) (Paulchen-Panther-2e83c587/e3587923-1587148622)
- Build time:  Apr 17 2020 19:14:31
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.5
- UI Lang:     auto (BrowserLang: de-DE)
- UI Access:   default
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (4.19.97+ (WS: 32))
- Browser:      Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.90 Safari/537.36 

Do you have an idea? :)
Thank you very much in advance.
This is an awesome project!!!

**Comment by Paulchen-Panther** [comment] 2020-05-10 10:41
> Sun 10 May 2020 10:11:15 BST: [hyperiond HYPERION] PriorityMuxer.cpp:238:setInputImage() Priority 100 is now inactive
> Sun 10 May 2020 10:11:16 BST: [hyperiond HYPERION] PriorityMuxer.cpp:238:setInputImage() Priority 100 is now active
> Sun 10 May 2020 10:11:17 BST: [hyperiond HYPERION] PriorityMuxer.cpp:238:setInputImage() Priority 100 is now inactive
> Sun 10 May 2020 10:12:22 BST: [hyperiond HYPERION] PriorityMuxer.cpp:238:setInputImage() Priority 100 is now active
> Sun 10 May 2020 10:12:23 BST: [hyperiond HYPERION] PriorityMuxer.cpp:238:setInputImage() Priority 100 is now inactive
> Sun 10 May 2020 10:12:24 BST: [hyperiond HYPERION] PriorityMuxer.cpp:238:setInputImage() Priority 100 is now active
> Sun 10 May 2020 10:12:25 BST: [hyperiond HYPERION] PriorityMuxer.cpp:238:setInputImage() Priority 100 is now inactive
> Sun 10 May 2020 10:12:27 BST: [hyperiond HYPERION] PriorityMuxer.cpp:238:setInputImage() Priority 100 is now active
> Sun 10 May 2020 10:12:28 BST: [hyperiond HYPERION] PriorityMuxer.cpp:238:setInputImage() Priority 100 is now inactive


It is not the v4l2 device that is to blame for your dropouts, but any external network source. The V4l2 priority is usually 240. You can find it [here](https://docs.hyperion-project.org/en/api/Guidelines.html#priority-guidelines)

**Comment by btk999** [comment] 2020-05-10 10:43
i changed this on my own for testing purposes. I switched it back to 240 but it makes no difference :(

**Comment by Paulchen-Panther** [comment] 2020-05-17 10:39
Please post the current debug log.

**Comment by btk999** [comment] 2020-05-17 13:11
> Please post the current debug log.

Its stil the same. 

Sun 17 May 2020 14:09:07 BST:  [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:333:setCurrentTime()> Set visible priority to 255
Sun 17 May 2020 14:09:08 BST:  [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:238:setInputImage()> Priority 100 is now active
Sun 17 May 2020 14:09:08 BST:  [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:333:setCurrentTime()> Set visible priority to 100
Sun 17 May 2020 14:09:10 BST:  [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:238:setInputImage()> Priority 100 is now inactive
Sun 17 May 2020 14:09:10 BST:  [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:333:setCurrentTime()> Set visible priority to 255
Sun 17 May 2020 14:09:12 BST:  [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:238:setInputImage()> Priority 100 is now active
Sun 17 May 2020 14:09:12 BST:  [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:333:setCurrentTime()> Set visible priority to 100
Sun 17 May 2020 14:09:14 BST:  [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:238:setInputImage()> Priority 100 is now inactive
Sun 17 May 2020 14:09:14 BST:  [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:333:setCurrentTime()> Set visible priority to 255
Sun 17 May 2020 14:09:15 BST:  [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:238:setInputImage()> Priority 100 is now active
Sun 17 May 2020 14:09:15 BST:  [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:333:setCurrentTime()> Set visible priority to 100
Sun 17 May 2020 14:09:16 BST:  [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:238:setInputImage()> Priority 100 is now inactive
Sun 17 May 2020 14:09:16 BST:  [hyperiond HYPERION] <DEBUG> <PriorityMuxer.cpp:333:setCurrentTime()> Set visible priority to 255

i recognized that the source disappearing in web interface remote control too:

![image](https://user-images.githubusercontent.com/20415739/82147797-85ee1600-9850-11ea-88f1-f4f0a76607e7.png)
![image](https://user-images.githubusercontent.com/20415739/82147812-a3bb7b00-9850-11ea-9305-a495d2166efa.png)

so appearing / disappearing continiously...

Do you have an idea?

**Comment by Paulchen-Panther** [comment] 2020-05-17 13:32
There is still a priority 100 in between. Is there another device running (Android, RPi etc.) or another process? And please always post the complete debug log.

**Comment by btk999** [comment] 2020-05-17 14:14
Ah sorry, the priority 100 was set manually by me for this device. I have set it back to default 240 now. There is no other device running, i attached a screenshot from TOP and syslog, and here is the complete debug log:
[hyperion.log](https://github.com/hyperion-project/hyperion.ng/files/4640383/hyperion.log)
[syslog.txt](https://github.com/hyperion-project/hyperion.ng/files/4640384/syslog.txt)
![htop](https://user-images.githubusercontent.com/20415739/82150809-71fae200-9859-11ea-9fc9-a23fc8ba5ba7.png)

**Comment by Paulchen-Panther** [comment] 2020-05-17 14:36
Can you export your current configuration and post it here?

**Comment by btk999** [comment] 2020-05-17 14:50
> Can you export your current configuration and post it here?

Sure:

**Comment by Paulchen-Panther** [comment] 2020-05-17 15:36
I would enlarge the area for signal detection a little.
This is yours:: https://prnt.sc/sifvnb
That is the default: https://prnt.sc/sig0hg

According to the code, however, this area should be ignored if signalDetection is false.
Either your grabber loses the signal and switches back and forth there is another malfunction with the grabber.

I have 4 grabbers here, including your utvf007, and none shows the explained problem. Very strange.

**Comment by btk999** [comment] 2020-05-17 15:44
The signaldetection to false in my config so i thought this settings are not relevant?
But i put the values back to default and enabled signal detection. It doesnt make a difference, stil getting the same entries in log file.

The strange thing is: This does not occur with hyperion classic version, so it might not be a hardware problem with the grabber?

**Comment by tpmodding** [comment] 2020-06-03 16:12
can you provide your config please

**Comment by dtydings** [comment] 2020-09-03 03:19
This keep happening to mine too. The grabber randomly starts and stops. When it stops, the led strip goes back to the setting it was on before. 

I'm running hyperion.ng on mac os. Sending E1.31 data to an ESP8266 running WLED. This problem started when I upgraded from old hyperion to NG. I thought I properly uninstalled the older hyperion so it wouldn't interfere with NG. I tried changing the priority of the grabber as well and no luck. Not sure what else to do here. Any help would be greatly appreciated!



2020-09-02T23:10:44.774`` hyperiond HYPERION.    : <DEBUG> PriorityMuxer.cpp:238:setInputImage() | Priority 100 is now inactive
2020-09-02T23:10:44.774 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:333:setCurrentTime() | Set visible priority to 255
2020-09-02T23:10:44.867 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:238:setInputImage() | Priority 100 is now active
2020-09-02T23:10:44.867 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:333:setCurrentTime() | Set visible priority to 100
2020-09-02T23:10:54.907 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:238:setInputImage() | Priority 100 is now inactive
2020-09-02T23:10:54.908 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:333:setCurrentTime() | Set visible priority to 255
2020-09-02T23:10:54.968 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:238:setInputImage() | Priority 100 is now active
2020-09-02T23:10:54.968 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:333:setCurrentTime() | Set visible priority to 100
2020-09-02T23:11:04.986 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:238:setInputImage() | Priority 100 is now inactive
2020-09-02T23:11:04.987 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:333:setCurrentTime() | Set visible priority to 255
2020-09-02T23:11:05.070 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:238:setInputImage() | Priority 100 is now active
2020-09-02T23:11:05.071 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:333:setCurrentTime() | Set visible priority to 100
2020-09-02T23:11:15.112 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:238:setInputImage() | Priority 100 is now inactive
2020-09-02T23:11:15.112 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:333:setCurrentTime() | Set visible priority to 255
2020-09-02T23:11:15.167 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:238:setInputImage() | Priority 100 is now active
2020-09-02T23:11:15.167 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:333:setCurrentTime() | Set visible priority to 100

**Comment by Zarkstar** [comment] 2020-12-03 02:54
I am running Hyperion on macOS and this happens to me as well... any fix for this? alpha 9 didn't solve it

**Comment by quietsnow** [comment] 2020-12-21 07:00
I'm having the same issue. I blew away the install because there were a number of other things on that pi -- and started fresh with Hyperbian. Still same issue -- Hyperion works just fine upon boot, for about a minute. Then it loses USB and never regains it.

**Comment by PrathikGopal** [comment] 2021-05-14 13:39
Same here on my rpi3b too. Any leads on this?

**Comment by quietsnow** [comment] 2021-05-14 13:41
Use the “remote” page to disable whatever is higher priority. Restart the services. Should come back up

**Comment by i7i5** [comment] 2021-05-22 08:19
Hello,
I'm facing the same problem.

```
Hyperion Server: 
- Build:           master (GitHub-98cb917/9199aa8-1621532405)
- Build time:      May 22 2021 07:35:21
- Git Remote:      https://github.com/hyperion-project/hyperion.ng.git
- Version:         2.0.0-alpha.9
- UI Lang:         auto (BrowserLang: de)
- UI Access:       default
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 3 (v7l)
- CPU Type:       Raspberry Pi 4 Model B Rev 1.2
- CPU Revision:   c03112
- CPU Hardware:   BCM2711
- Kernel:         linux (5.10.17-v7l+ (WS: 32))
- Qt Version:     5.11.3
- Python Version: 3.7.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
```

I use the 10$ grabber (RULLZ 4K Video Capture Card USB 3,0 2,0 HDMI Video Grabber Box) which is recommented here: https://hyperion-project.org/forum/index.php?thread/10564-%C3%BCbersicht-tests-digitale-grabber/.

![Error](https://user-images.githubusercontent.com/9058776/119219683-10fa8f80-bae7-11eb-8534-38488e30ab93.gif)

**Comment by zufl** [comment] 2021-05-22 08:36
Hi,

I had the same issue, also with the RULLZ 4k grabber and Raspberry Pi 4. Connecting the grabber to an active USB hub also did not help.
Compiling from the latest sources solved the issue for me. The grabber is now running stable. Strangely, this does not seem to help @i7i5.

**Comment by i7i5** [comment] 2021-05-22 09:04
@zufl Sadly recompiling didn't help - tried it today for several times :/
I'm not quiet sure if there is a correlation to installed software. In the last weeks the only thing I installed manually was `2021-05-02 07:47:53 install libseccomp-dev:armhf <none> 2.3.3-4` I think.

Before yesterday I used the analog way with hdmi to analog to grabber. Im facing this issue since ~3-4 weeks what was the reason to change to the digital way. I thought that smth in the analog chain broke.

**Comment by zufl** [comment] 2021-05-24 11:22
Turns out it was only stable for one evening for me too. :-/

I did some further investigations and the hardware is not delivering new frames from time to time but recovers after 1-2s. It happens more often with higher resolutions so I think it is somehow related to bandwidth. I did some code changes on a fork, feel free to try it out [here](https://github.com/zufl/hyperion.ng). I can open a pull request if this also improves the situation for others.

You can compile the fork and add the following parameters to the hyperion config:

```
"grabberV4L2": {
...
    "pixelFormat": "mjpeg"
},
"instCapture": {
...
    "v4lTimeout": 1000
},
```
I also made the timeout customizable. Maybe it's not needed anymore, but you could give it a try and increase it if necessary (default is 1000ms). I saw some timeout every couple of minutes which was not noticeable visually if hyperion would not have disabled the input.

**Comment by i7i5** [comment] 2021-05-24 18:23
Ok I tried your fork. Without setting the v4lTimeout it starts flickering again :/ I dont know why, I cant set the v4lTimeout. After import it seems to get ignored. 

For you the changes are working now? After the first compilation it worked for like 10mins. But now after 1-2mins it fails again.

What are your settings, I have like everything on auto atm.

**Comment by zufl** [comment] 2021-05-24 20:20
Yes, for me it's working pretty well, I get about one reconnect per hour when not increasing the timeout. I commited a change that allows editing the v4lTimeout in the webinterface. There seemed to be an issue before to change it via the config.

I use a resolution of 640x480 with 25FPS. It also helps to stop any other application, for me an instance of Kodi made things much worse.

**Comment by i7i5** [comment] 2021-05-25 19:57
I don't know... For me this doesn't work. It's not device related, I did reconnect my analog hardware (stk1160) but this doesn't work either. I also tried to patch back to v8 but only get a ton of build errors. So I'm stuck with this version >.>

I also followed my syslog with `tail -f /var/log/syslog` but there's nothing special like a USB diconnect or smth. Only hyperiong log spam :/ Kodi or simular isn't installed, just home assistant and pihole but both are dockerized. Hyperion is the only thing installed on this pi.

**Comment by Rogi66** [comment] 2021-06-12 12:52
same issue here, i also exchanged the hdmi grabber...the screen freezes and the usb capture device disappears. :(

**Comment by i7i5** [comment] 2021-07-02 15:07
I don't have any solution. My raspi is up to date, so I guess it's some issue with other libs. I'm stuck waiting for a new version hoping that it will fix smth.

**Comment by Lord-Grey** [comment] 2021-07-18 17:04
Can you re-test with alpha10 and report back please, if the issue is still present?

**Comment by i7i5** [comment] 2021-07-19 19:34
I've tried it for over an hour without crashing, seems to be fixed for me. Thanks a lot! :)

**Closed** 2021-07-19 20:38 UTC
Labels: bug, needs investigation
