### ISSUE TITLE
Smooting active does not allow to set a color via the web interface

### ISSUE THREAD

**Issue by Nears** [hyperion-project/hyperion.ng#1240] opened 2021-05-12 18:28 UTC
- [x] I confirm that this is an issue rather than a question.

## Bug report
Smooting active does not allow to set a color via the web interface, leds will stay black

#### Steps to reproduce
installation of hyperion.ng alpha 9

#### What is expected?
leds should light up with the color set via the web interface (remote control -> colors/effects 

#### What is actually happening?
Leds stay black, but if smoothing is deactivated LEDs get on after the color is changed

#### System

Hyperion Server: 
- Build:           (HEAD detached at 83338dc3) (Paulchen Panther-ca50487e/83338dc3-1605733041)
- Build time:      Nov 18 2020 21:34:12
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.9
- UI Lang:         en (BrowserLang: de)
- UI Access:       expert
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 3 (v7l)
- CPU Type:       Raspberry Pi 4 Model B Rev 1.1
- CPU Revision:   c03111
- CPU Hardware:   BCM2711
- Kernel:         linux (5.10.17-v7l+ (WS: 32))
- Qt Version:     5.7.1
- Python Version: 3.5.3
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0

**Comment by Lord-Grey** [comment] 2021-08-01 19:26
Duplicate of #1098

**Closed by Lord-Grey** 2021-08-01 19:26 UTC
Labels: Waiting For Review
