### ISSUE TITLE
Invalid response from Philips Hue API

### ISSUE THREAD

**Issue by b1rdhous3** [hyperion-project/hyperion.ng#310] opened 2016-12-04 20:15 UTC
```
"device" :
        {
                "name"       : "DefaultHyperionConfig",
                "type"       : "philipshue",
                "output":"192.168.0.176",
                "lightIds":[5],
                "username"     : "xxxxxxxxxxx",
                "rate"       : 1000000,
                "colorOrder" : "rgb",
                "switchOffOnBlack":false
        }
```

When I start hyperion I get following error:
[HYPERIOND LedDevice] <ERROR> saveStates(nLights=1): got no state for light from http://192.168.0.176/api/d50ctoU/lights/5
[HYPERIOND LedDevice] <ERROR> saveStates(nLights=1): got invalid response from light http://192.168.0.176/api/d50ctoU/lights/5.

But when I open the link in my browser I get a respone:
`{"state":{"on":true,"bri":104,"hue":39392,"sat":13,"effect":"none","xy":[0.3691,0.3719],"ct":231,"alert":"none","colormode":"xy","reachable":true},"type":"Extended color light","name":"Computer","modelid":"LST002","manufacturername":"Philips","uniqueid":"00:17:88:01:01:1f:4b:29-0b","swversion":"5.50.2.19072"}`

Some an idea?

**Comment by brindosch** [comment] 2016-12-04 20:24
@ntim the Hue Guy :)
Would be great if you could check against current development.

**Comment by redPanther** [comment] 2016-12-05 21:59
It is possible, that something went wrong when migrating this to new qt json api

**Comment by penfold42** [comment] 2016-12-05 22:04
@b1rdhous3

Does running with --debug provide more output ?

**Comment by redPanther** [comment] 2016-12-05 22:13
we can add better error output:
in LedDevicePhilipsHue.cpp line 373 Error(... 
replace  it with:
```
			Error(_log, "saveStates(nLights=%d): got invalid response from light %s. (error:%s, offset:%d)",
			  nLights, getUrl(getRoute(lightIds.at(i))).toStdString().c_str(), error.errorString().toLocal8Bit().constData(), error.offset );
```

**Comment by b1rdhous3** [comment] 2016-12-05 22:15
No more output with debug. 
I will compile and run it again @redPanther

**Comment by redPanther** [comment] 2016-12-05 22:17
thx for helping to find the bug :+1:

**Comment by b1rdhous3** [comment] 2016-12-05 22:39
<ERROR> saveStates(nLights=1): got invalid response from light http://192.168.0.176/api/d50ctoH6nu8hwbzMLQMa7ASjYX06ES2FM37IUIAU/lights/5. (error:illegal value, offset:0)


I only got "invalid response" once. The other error is happening all the time.

**Comment by Paulchen-Panther** [comment] 2016-12-06 21:12
Es könnte sein das sich bei der Übersetzung von JsonCPP zu QTJson ein Fehler in der Hue Device Class eingeschlichen hat. Dies war am schwersten zu übersetzen. Werde demnächst noch mal über die Class schauen. Da ich leider keine Hues besitze kann ich die sache nicht testen. Sorry

**Comment by Paulchen-Panther** [comment] 2016-12-06 21:38
Can you please insert this :

`json = reader.object();`

in[ LedDevicePhilipsHue.cpp on Line 369](https://github.com/hyperion-project/hyperion.ng/blob/master/libsrc/leddevice/LedDevicePhilipsHue.cpp#L369)

**Comment by b1rdhous3** [comment] 2016-12-06 23:12
Kein Problem, danke dass du dich kümmerst @Paulchen-Panther .
ZUm testen bin ich ja da. 

Leider gibt json = reader.object() keinen neuen Output oder ein anderes Ergebnis.

**Comment by b1rdhous3** [comment] 2016-12-06 23:25
No changes with that line

**Comment by ntim** [comment] 2016-12-07 15:40
I will try the new code at home

**Comment by ntim** [comment] 2016-12-08 09:34
Works fine on my RPi3 with OSMC and 2 lights. Can you log the raw response in line 373? Not the parsed object since that obviously failed. It might not look the same as in your browser.

**Comment by b1rdhous3** [comment] 2016-12-08 21:04
@ntim thank you for your answer but sadly I don't know how to display the raw data (var response?) at that point. I always get errors while compiling if i try 

Can you please provide the line? Thanks!

**Comment by ntim** [comment] 2016-12-08 23:39
Ok, will look into it tomorrow.

**Comment by b1rdhous3** [comment] 2016-12-08 23:45
Thanks!

**Comment by ntim** [comment] 2016-12-09 09:06
Hi, I put the following code after line 366:

`std::cout << response.constData() << std::endl;`

This gives me e.g. the following output:

> {"state":{"on":true,"bri":254,"hue":13768,"sat":56,"effect":"none","xy":[0.4578,0.4142],"alert":"none","colormode":"xy","reachable":true},"type":"Color light","name":"LivingColors Links","modelid":"LLC011","manufacturername":"Philips","uniqueid":"00:17:88:01:00:c1:63:5d-0b","swversion":"5.23.1.13452"}

Today I also got the same problem, it says, the problem is that in this loop the retrieval of the json object is missing. Fixed it and submitted a pull request.

**Comment by b1rdhous3** [comment] 2016-12-09 09:22
Hm, that it the same @Paulchen-Panther suggested and I tried that as well with no effect. I will check that again and also the logging. I will come back to this.

**Comment by ntim** [comment] 2016-12-09 13:29
It is definitely missing anyway, may not be the fix to your problem after all but with the additional logging we should get going in the right direction .

**Comment by redPanther** [comment] 2016-12-18 18:50
@b1rdhous3 has state changed here? if not, can you provide logs?

e.g.
> Hi, I put the following code after line 366:
> std::cout << response.constData() << std::endl;

**Comment by b1rdhous3** [comment] 2016-12-18 22:59
Havn't tested it yet. Will do in the next days.

**Comment by redPanther** [comment] 2017-01-03 08:09
And how the tests going on? Would be good to know if hues work again

**Comment by brindosch** [comment] 2017-01-20 14:42
@b1rdhous3 
i consider to close this issue :)

**Comment by redPanther** [comment] 2017-01-21 22:29
I close the issue. If we have trouble here we can make a new issue with latest info's

**Closed by redPanther** 2017-01-21 22:29 UTC
Labels: Backlog
