### ISSUE TITLE
hyperiond crashed with a segfault, but I could not reproduce it

### ISSUE THREAD

**Issue by deisi** [hyperion-project/hyperion.ng#772] opened 2020-04-18 07:48 UTC
- [x] I confirm that this is an issue rather than a question.

## Bug report
For what it's worth,
Up on saving LED Layout (Frame)
I changed all non advanced availabe parameters, hyperiond crashed with dmesg
```
[146030.413167] Effect[6315]: segfault at a9 ip 00007f732a1d3734 sp 00007f731ce439f8 error 4 in libpython3.5m.so.1.0[7f7329feb000+3c5000]
[146030.413174] Code: 48 89 53 f0 48 89 4d 08 48 89 0a 48 89 6b e8 48 83 c8 02 48 89 43 f8 48 83 c4 08 31 c0 5b 5d c3 66 0f 1f 44 00 00 48 8b 47 08 <f6> 80 a9 00 00 00 40 74 33 53 48 8b 80 48 01 00 00 48 89 fb 48 85
```
I used alpha5

#### Steps to reproduce
Tryed to to the same, but it didn't happen
- compile alpha 5 with docker_compile.sh
- install 
- configure LED
- save > crash

#### What is expected?
Shouldn't segfault I guess

#### What is actually happening?
Segfaults

#### System

Hyperion Server: 
- Build:       master (Paulchen-Panther-2e83c58/e358792-1587148622)
- Build time:  Apr 18 2020 07:29:11
- Git Remote:  https://github.com/hyperion-project/hyperion.ng.git
- Version:     2.0.0-alpha.5
- UI Lang:     auto (BrowserLang: en-US)
- UI Access:   default
- Avail Capt:  v4l2,framebuffer,x11,qt

Hyperion Server OS: 
- Distribution: Ubuntu 19.10
- Arch:         x86_64
- Kernel:       linux (5.3.0-46-generic (WS: 64))
- Browser:      Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0

**Comment by Paulchen-Panther** [comment] 2020-04-18 07:55
It would be nice if you also filled out the rest of the issue template.

**Comment by deisi** [comment] 2020-04-18 08:45
Could you be more specific? I filled in all of the information I have.

**Comment by Paulchen-Panther** [comment] 2020-04-18 08:49
![download](https://user-images.githubusercontent.com/16664240/79632847-35f13600-8162-11ea-81e6-c3cb9281ad9b.png)

**Comment by deisi** [comment] 2020-04-18 08:52
Okay, now I could reproduce by changing the LED Frame config back and forth a couple of times, and then it crashed again.

Sry, look into it a little later, but its unclear to me what Your system information - please copy paste "System info (Github Issue)" section from web configuration/system/about  means.
what is this reffering to? what is `web configuration/system/about`

**Comment by Paulchen-Panther** [comment] 2020-04-18 08:59
![Screenshot](https://user-images.githubusercontent.com/16664240/79633121-b95f5700-8163-11ea-8af8-fde807eb5a49.png)

**Comment by Paulchen-Panther** [comment] 2020-04-18 10:56
> Okay, now I could reproduce by changing the LED Frame config back and forth a couple of times, and then it crashed again.

I would like to point out that hyperion.ng is still in the alpha phase. Since errors can still occur when saving the settings. However, no settings should be missing in the database, so everything is read correctly when hyperion is restarted.
If you can, we would be happy to receive a gdb backtrace log. If you are not able to do this, please do not ask how. Ask an internet search engine.

Regards Paulchen-Panther

**Comment by deisi** [comment] 2020-04-18 13:22
> I would like to point out that hyperion.ng is still in the alpha phase

That is why I reported the error in the first place. I try to be helpful.

The description `Your system information - please copy paste "System info (Github Issue)" section from web configuration/system/about ` is all but clear. Maybe consider change it to something like

In the web interface of the Hyperion config got to System > About Hyperion and Paste the content of "System info (Github Issue)" here

The way this is currently formatted hints towards a Path with the `/` so I started to look in the code tree for this and then in the configuration folder. Also calling this System info (Gitub Issue) isn't really helping either, as I was then searching here in the Github Issue for something that could help me. Just calling the webiterface web isn't clear to an outsider as well, as web could mean a lot of things for a lot of people. Again, I try to be helpful here by giving feedback, I make no demands or accusations.

**Comment by deisi** [comment] 2020-04-18 14:31
```
Thread 42 "Effect" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffb3fff700 (LWP 6671)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff4ac5899 in __GI_abort () at abort.c:79
#2  0x00007ffff4b3038e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff4c593a5 "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff4b384dc in malloc_printerr (str=str@entry=0x7ffff4c57542 "free(): invalid size") at malloc.c:5332
#4  0x00007ffff4b39d0c in _int_free (av=<optimized out>, p=0x7fffcc003290, have_lock=0) at malloc.c:4177
#5  0x00007ffff7a31b28 in ?? () from /usr/share/hyperion/bin/../lib/libpython3.5m.so.1.0
#6  0x00007ffff7b37647 in PyInterpreterState_Clear () from /usr/share/hyperion/bin/../lib/libpython3.5m.so.1.0
#7  0x00007ffff7b4242f in Py_EndInterpreter () from /usr/share/hyperion/bin/../lib/libpython3.5m.so.1.0
#8  0x00005555556634a8 in Effect::run() ()
#9  0x00007ffff5098d48 in ?? () from /usr/share/hyperion/bin/../lib/libQt5Core.so.5
#10 0x00007ffff61ed669 in start_thread (arg=<optimized out>) at pthread_create.c:479
#11 0x00007ffff4bc2323 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Apparently I'm missing some debug symbols here. Lets see If I find out what else is needed.

**Comment by Paulchen-Panther** [comment] 2020-04-18 14:45
Thanks for the log.
Can you please compile Hyperion with debug symbols and create a gdb backtrace log again?

**Comment by Paulchen-Panther** [comment] 2020-04-18 14:46
https://prnt.sc/s1te5r

**Comment by deisi** [comment] 2020-04-18 14:47
I'm on it, just give me some time as I'm digging through this.

**Comment by Paulchen-Panther** [comment] 2020-04-18 14:51
So at first glance it looks like that after saving the settings in the WebUI the background effect tries to write but the device is no longer open (normal process: device close -> settings change -> device open).

**Comment by Paulchen-Panther** [comment] 2020-04-18 14:53
You could try the following. Deactivate the background effect and repeat your steps. if hyperion no longer crashes it is the background effect.

**Comment by deisi** [comment] 2020-04-18 15:01
I can't reproduce this in a reliable way. I stated it and got

```
#0  __libc_write (nbytes=5144, buf=0x7fffcc0655f8, fd=48) at ../sysdeps/unix/sysv/linux/write.c:26
#1  __libc_write (fd=48, buf=0x7fffcc0655f8, nbytes=5144) at ../sysdeps/unix/sysv/linux/write.c:24
#2  0x00007ffff720df15 in ?? () from /home/malte/anaconda3/lib/libQt5Network.so.5
#3  0x00007ffff720c2b9 in ?? () from /home/malte/anaconda3/lib/libQt5Network.so.5
#4  0x00007ffff7200839 in ?? () from /home/malte/anaconda3/lib/libQt5Network.so.5
#5  0x00007ffff71ff1da in ?? () from /home/malte/anaconda3/lib/libQt5Network.so.5
#6  0x00005555556ad694 in QtHttpClientWrapper::onReplySendDataRequested() ()
#7  0x00007ffff6b3fdc3 in QMetaObject::activate(QObject*, int, int, void**) () from /home/malte/anaconda3/lib/libQt5Core.so.5
#8  0x00005555556adc5b in QtHttpClientWrapper::sendReplyToClient(QtHttpReply*) ()
#9  0x00005555556af511 in QtHttpClientWrapper::onClientDataReceived() ()
#10 0x00007ffff6b3fdc3 in QMetaObject::activate(QObject*, int, int, void**) () from /home/malte/anaconda3/lib/libQt5Core.so.5
#11 0x00007ffff71ffcaf in ?? () from /home/malte/anaconda3/lib/libQt5Network.so.5
#12 0x00007ffff720042c in ?? () from /home/malte/anaconda3/lib/libQt5Network.so.5
#13 0x00007ffff720cc9a in ?? () from /home/malte/anaconda3/lib/libQt5Network.so.5
#14 0x00007ffff789bca0 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /home/malte/anaconda3/lib/libQt5Widgets.so.5
#15 0x00007ffff78a1b19 in QApplication::notify(QObject*, QEvent*) () from /home/malte/anaconda3/lib/libQt5Widgets.so.5
#16 0x00007ffff6b2b28a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/malte/anaconda3/lib/libQt5Core.so.5
#17 0x00007ffff6b58142 in ?? () from /home/malte/anaconda3/lib/libQt5Core.so.5
#18 0x00007ffff3d3ad1b in g_main_context_dispatch () from /home/malte/anaconda3/lib/./libglib-2.0.so.0
#19 0x00007ffff3d3af61 in g_main_context_iterate.isra () from /home/malte/anaconda3/lib/./libglib-2.0.so.0
#20 0x00007ffff3d3afee in g_main_context_iteration () from /home/malte/anaconda3/lib/./libglib-2.0.so.0
#21 0x00007ffff6b578df in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
```
right away. However now I started it again and its not crashing as of yet. 

btw: https://prnt.sc/s1te5r was what I did obtaining the backtrace without debug symbols. I guess, if you compile with docker debug symbols are not available. However, I have compiled on the host now and I think it works.

**Comment by Paulchen-Panther** [comment] 2020-04-18 15:05
Then I dont know anymore. Maybe it's because of the QT5 version!?! We should keep an eye on the problem.
Thanks again for your good suggestion for the issue template and your time.

**Comment by deisi** [comment] 2020-04-18 15:27
Now I just waited a little and got wile I was AFK.

```
[Switching to Thread 0x7fffe1ab6700 (LWP 24404)]
__libc_write (nbytes=34036, buf=0x7fffcc115cb8, fd=57) at ../sysdeps/unix/sysv/linux/write.c:26
26	../sysdeps/unix/sysv/linux/write.c: No such file or directory.
(gdb) bt
#0  __libc_write (nbytes=34036, buf=0x7fffcc115cb8, fd=57) at ../sysdeps/unix/sysv/linux/write.c:26
#1  __libc_write (fd=57, buf=0x7fffcc115cb8, nbytes=34036) at ../sysdeps/unix/sysv/linux/write.c:24
#2  0x00007ffff720df15 in ?? () from /home/malte/anaconda3/lib/libQt5Network.so.5
#3  0x00007ffff720c2b9 in ?? () from /home/malte/anaconda3/lib/libQt5Network.so.5
#4  0x00007ffff7200839 in ?? () from /home/malte/anaconda3/lib/libQt5Network.so.5
#5  0x00007ffff71ff1da in ?? () from /home/malte/anaconda3/lib/libQt5Network.so.5
#6  0x00005555556ad694 in QtHttpClientWrapper::onReplySendDataRequested() ()
#7  0x00007ffff6b3fdc3 in QMetaObject::activate(QObject*, int, int, void**) () from /home/malte/anaconda3/lib/libQt5Core.so.5
#8  0x00005555556adc5b in QtHttpClientWrapper::sendReplyToClient(QtHttpReply*) ()
#9  0x00005555556af511 in QtHttpClientWrapper::onClientDataReceived() ()
#10 0x00007ffff6b3fdc3 in QMetaObject::activate(QObject*, int, int, void**) () from /home/malte/anaconda3/lib/libQt5Core.so.5
#11 0x00007ffff71ffcaf in ?? () from /home/malte/anaconda3/lib/libQt5Network.so.5
#12 0x00007ffff720042c in ?? () from /home/malte/anaconda3/lib/libQt5Network.so.5
#13 0x00007ffff720cc9a in ?? () from /home/malte/anaconda3/lib/libQt5Network.so.5
#14 0x00007ffff789bca0 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /home/malte/anaconda3/lib/libQt5Widgets.so.5
#15 0x00007ffff78a1b19 in QApplication::notify(QObject*, QEvent*) () from /home/malte/anaconda3/lib/libQt5Widgets.so.5
#16 0x00007ffff6b2b28a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/malte/anaconda3/lib/libQt5Core.so.5
#17 0x00007ffff6b58142 in ?? () from /home/malte/anaconda3/lib/libQt5Core.so.5
#18 0x00007ffff3d3ad1b in g_main_context_dispatch () from /home/malte/anaconda3/lib/./libglib-2.0.so.0
#19 0x00007ffff3d3af61 in g_main_context_iterate.isra () from /home/malte/anaconda3/lib/./libglib-2.0.so.0
#20 0x00007ffff3d3afee in g_main_context_iteration () from /home/malte/anaconda3/lib/./libglib-2.0.so.0
#21 0x00007ffff6b578df in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
```

**Comment by tpmodding** [comment] 2020-06-03 16:21
which led device you use?
is your pi connected to a network (wifi or wired doesnt matter)

**Comment by deisi** [comment] 2020-06-05 11:00
I use: [WS2812 B](https://www.amazon.de/gp/product/B00S1AMV3U/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1) but there is no Raspberry-Pi involved. I use an Arduino to control the LEDs.

**Comment by m-seker** [comment] 2020-07-04 19:26
@deisi Your first stack trace may have already been fixed with :

https://github.com/hyperion-project/hyperion.ng/pull/850

The other stack traces are different than the first one. You didn't provide what signal caused those crashes, there is a line in the GDB output that mentiones the causing signal, please report that as well.

I suspect that signal will be SIGPIPE, not SIGABRT or SIGSEGV. If this is the case, that happens only because you run it inside GDB. GDB catches the signal before we do in the application and stops execution.

So, what you can try is :
- Checkout latest master and build it.
- Try running without GDB.
- Try to reproduce the crash.

If it runs good, we are good. If it still crashes :
- Run GDB : ````gdb bin/hyperiond````
- Ignore SIGPIPE in GDB : ````handle SIGPIPE nostop noprint pass````
- Run hyperion : ````run -d -u user````
- Try to reproduce the crash.
- Tell us what crash do you see.

**Closed** 2021-03-27 14:17 UTC
Labels: bug, needs investigation
