### ISSUE TITLE
Hyperion can't enable screen capture on Ubuntu 22.04

### ISSUE THREAD

**Issue by Krypt0nC0R3** [hyperion-project/hyperion.ng#1604] opened 2023-04-13 06:51 UTC
- [x] I confirm that this is an issue rather than a question.

## Bug report
Hyperion can't enable screen capture on Ubuntu 22.04

#### Steps to reproduce
Follow the official installation guide

#### What is expected?
Screen capture is enabled and system is ready to connect led strip
![image](https://user-images.githubusercontent.com/46594859/231675966-29fe53ce-3b7a-4c51-91f5-0878aec3c657.png)

#### What is actually happening?
Screen capture is disabled and "No capture device discovered"
![image](https://user-images.githubusercontent.com/46594859/231675721-9230bd29-7986-48e0-bfd4-c5a9c5768fef.png)

![image](https://user-images.githubusercontent.com/46594859/231676040-61278d22-910f-4606-af7e-73f28f68f8d3.png)

#### System

```
Hyperion Server:
- Build:              ()
- Build time:        Feb 19 2023 16:07:12
- Git Remote:        
- Version:           2.0.15
- UI Lang:           en (BrowserLang: ru-RU)
- UI Access:         advanced
- Avail Screen Cap.: framebuffer,x11,xcb,qt
- Avail Video  Cap.: v4l2
- Avail Audio  Cap.: audio
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       /home/media/.hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      Ubuntu 22.04.2 LTS
- Architecture:      x86_64
- CPU Model:         Intel(R) Celeron(R) G5905 CPU @ 3.50GHz
- CPU Type:          165
- Kernel:            linux (5.19.0-38-generic (WS: 64))
- Root/Admin:        false
- Qt Version:        5.15.3
- Python Version:    3.10.6
- Browser:           Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
```

**Comment by Lord-Grey** [comment] 2023-04-15 17:14
@Krypt0nC0R3 Per default Ubuntu 22.04 makes use of the Wayland Window Manager which is currently not supported by Hyperion. That is why no capture device is discovered, given there is no capture support in this configuration.

Log in with the "XOrg" Window Manager and you will have X11, XCB and Qt screen-grabber available as usual.

**Comment by Lord-Grey** [comment] 2023-05-07 13:26
Closing, as no feedback.

**Closed by Lord-Grey** 2023-05-07 13:26 UTC
Labels: Waiting for Input

**Comment by nocin** [comment] 2023-10-13 19:31
Hi @Lord-Grey,

today I did a fresh install of Linux Mint 21.2 and I got the same result: "no capture device discovered".
Allthough Mint is using X11 afaik.

Then I remembered, a few years ago I already had Hyperion working on Linux Mint. 
So I downloaded an older release and voila, it is working. 
![image](https://github.com/hyperion-project/hyperion.ng/assets/35531968/34c1816e-569e-46f0-a160-2abe26bde2b3)

This is what I found out:

- Hyperion-2.0.0-alpha.9-Linux-x86_64   <------ works!
- Hyperion-2.0.0-alpha.10-Linux-x86_64 <------ works!
- Hyperion-2.0.0-alpha.11-Linux-x86_64 <------ seems like beginnig with this version, the capture device discovering is broken
- Hyperion-2.0.12-Linux-x86_64              <------ curent release, which does not work as well

I'm also running a HTPC which is a Proxmox (Debian) System. There I noticed the same problem a while ago. Updating to a new version broke the screen grabber detection. So I just did the classic thing "never change a running system". Just checked on my HTPC and it is still running on version 2.0.0-alpha.9. So the issue seems to be on Debian/Ubuntu/Linux Mint.

May be this will help, reproducing the issue.

Thanks & Regards
Nico

**Comment by Lord-Grey** [comment] 2023-10-14 11:23
@nocin  Which MINT 21.2 edition did you install/run?

**Comment by nocin** [comment] 2023-10-14 14:10
Hi @Lord-Grey,

running the Cinnamon version.
![image](https://github.com/hyperion-project/hyperion.ng/assets/35531968/b31ab13e-9ee7-4b8b-a026-4eb1d7824175)

Thank you for taking up the topic here again.

BR, Nico

**Comment by Lord-Grey** [comment] 2023-10-19 19:08
@nocin 

I installed a Mint 21.2 Cinnamon and Hyperion via the Hyperion apt server and there is not issue using the x11 grabber:

![image](https://github.com/hyperion-project/hyperion.ng/assets/48840279/3c268ef1-0e1e-4560-8241-cb0256b4e940)

Might be good to understand what you changed after the installation.
I assume you start Hyperion from command-line or via the icon, correct?
If you start via systemctl you must have DISPLAY set. if not then this is the issue.

In addition ,you might do the following command via a terminal and share the output:

```
echo $DISPLAY
echo $XDG_SESSION_TYPE
echo $WAYLAND_DISPLAY
```
