### ISSUE TITLE
Can't install on Fedora 36, unmet dependency

### ISSUE THREAD

**Issue by kennethso168** [hyperion-project/hyperion.ng#1475] opened 2022-06-07 15:20 UTC
- [x] I confirm that this is an issue rather than a question.

## Bug report

Tried to install Hyperion-2.0.13-Linux-x86_64.rpm downloaded from release on my Fedora 36 system, but it doesn't install.

#### Steps to reproduce

```
$ sudo dnf install Hyperion-2.0.13-Linux-x86_64.rpm
Last metadata expiration check: 0:26:49 ago on Tue Jun  7 22:52:29 2022.
Error: 
 Problem: conflicting requests
  - nothing provides libpython3.5m.so.1.0()(64bit) needed by hyperion-2.0.13-1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

I think the build should switch to python 3.10 as this is the python version used on Fedora 36?

**Comment by joe23rep** [comment] 2022-07-28 22:03
same issue on manjaro

**Comment by nonamewastaken** [comment] 2022-08-06 12:10
I have the same issue. However I doubt that python is the only issue here, as after removing the dependency via rpmrebuild and installing the newer version of py I still am unable to start the (now fully installed) software.

**Comment by mooreye** [comment] 2022-09-06 17:35
Can confirm, a pity Hyperion isn't available as flatpak, this would ease installation and updating

**Comment by iroCheese** [comment] 2022-12-22 10:24
I can confirm the same problem is still present with Fedora 37
```
sudo dnf install Hyperion-2.0.14-Linux-x86_64.rpm
Last metadata expiration check: 0:40:03 ago on Do 22 Dez 2022 10:42:09 CET.
Error: 
 Problem: conflicting requests
  - nothing provides libpython3.5m.so.1.0()(64bit) needed by hyperion-2.0.14-1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by EddoWagt** [comment] 2023-04-27 17:31
Has anyone found a fix for this yet? Trying to make my backlight work, but can't find any application which works with wayland and fedora

**Comment by VitalyVaryvdin** [comment] 2023-10-07 18:46
Hyperion is the only software that worked perfect for me but doesn't since I moved to Fedora. Sad to see this issue unattended for such a long time.

**Comment by mooreye** [comment] 2023-10-07 20:24
> Hyperion is the only software that worked perfect for me but doesn't since I moved to Fedora. Sad to see this issue unattended for such a long time.

Until this is fixed, you may have luck with building podman (docker) image I constructed, see here: https://github.com/hyperion-project/hyperion.ng/issues/1096#issuecomment-1250227348

**Comment by Paulchen-Panther** [comment] 2023-10-08 07:40
Work in progress: [https://releases.hyperion-project.org/](https://releases.hyperion-project.org/)

**Comment by VitalyVaryvdin** [comment] 2023-10-08 08:44
> > Hyperion is the only software that worked perfect for me but doesn't since I moved to Fedora. Sad to see this issue unattended for such a long time.
> 
> Until this is fixed, you may have luck with building podman (docker) image I constructed, see here: [#1096 (comment)](https://github.com/hyperion-project/hyperion.ng/issues/1096#issuecomment-1250227348)

Thanks for the solution, but apparently there's dnf repository available. Didn't see for some reason

> Work in progress: https://releases.hyperion-project.org/

Thanks. That's working now. Running on X11 though, but I'm fine with that

**Closed** 2024-01-19 15:06 UTC
Labels: needs investigation

**Comment by kennethso168** [comment] 2024-01-19 15:20
I'm no longer using Fedora or Hyperion, but glad to see the progress. Others concerned may see if this works.
