### ISSUE TITLE
Crash when X11 server is not available

### ISSUE THREAD

**Issue by Forceu** [hyperion-project/hyperion.ng#892] opened 2020-07-21 08:23 UTC
- [x] I confirm that this is an issue rather than a question.

I am running Hyperion on a headless x64 server. The server is connected to a TV and I have a script that creates an X11 instance with Kodi, which will be closed once I finished watching something. Platform Capture is set to on and X11. Once I close the X11 server, hyperion crashes. Hyperion is unable to start until an X11 instance is created again.

## Bug report

Hyperion crashes / is unable to start when no X11 server is available and Platform Capture with X11 is activated

#### Steps to reproduce

- Install on headless server
- Use Platform Capture X11
- Stop X11 instance

#### What is expected?

- Hyperion should deactivate the Platform Capture module and start / continue normally

#### What is actually happening?

- Hyperion crashes and is unable to start

> [hyperiond X11GRABBER] <ERROR> Unable to open display
> [hyperiond X11GRABBER] <ERROR> :0
> Segmentation fault (core dumped)

#### System

Hyperion Server: 
- Build:       (HEAD detached at f5583de8) (Sersch-f7865b45/f5583de8-1590611619)
- Build time:  May 27 2020 20:36:52
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.6
- UI Lang:     auto (BrowserLang: en-GB)
- UI Access:   default
- Avail Capt:  v4l2,framebuffer,x11,qt

Hyperion Server OS: 
- Distribution: Ubuntu 18.04.4 LTS
- Arch:         x86_64
- Kernel:       linux (5.6.17-050617-generic (WS: 64))
- Browser:      Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36

**Comment by m-seker** [comment] 2020-07-21 15:23
There are 2 issues here :

1 - Hyperion crashes when X disconnects. Can you share debug logs ? I think Hyperion exits instead of crashing because of the following :

https://github.com/freedesktop/xorg-lib-libX11/blob/20a3f99eba5001925b8b313da3accb7900eb1927/src/XlibInt.c#L1472

So, basically, server disconnection is a fatal IO error and XLib forces the application to exit. Notice that this is true regardless of setting your own error handler or using the default one. That means any application that uses display should exit if X disconnects.

2 - Hyperion doesn't start when X is not available. This is indeed a bug. Fixing it will make Hyperion start correctly even if there is no X server but the problem is there is no followup code to start the capturing again once X becomes available.

For the second one, it should not be hard to put some kind of a timer to periodically check if X is available.

For the first problem, I don't see any sane way. Forking another Hyperion in the custom event handler just before XLib forces us to exit ? Maybe upgrading to xcb all together ? @Paulchen-Panther what do you think ?

Here is a good read for who doesn't hate XLib enough : https://www.remlab.net/op/xlib.shtml

**Comment by m-seker** [comment] 2020-08-04 05:40
Last status : XCB grabber implemented. Now I will look for a way to get rid of QApplication dependency because it shuts  application down when the X connection is broken. If it works, it works, Otherwise this issue will be closed as is.

**Comment by Forceu** [comment] 2020-08-04 08:57
Sounds great, thank you for your work and effort! :)

**Closed** 2021-07-18 16:46 UTC
Labels: bug
