### ISSUE TITLE
high CPU after pi update

### ISSUE THREAD

**Issue by T-IOOO** [hyperion-project/hyperion.ng#974] opened 2020-08-18 09:39 UTC
- [x] I confirm that this is an issue rather than a question.

## Bug report
After running "sudo apt-get update" and "sudo apt-get upgrade", hyperiond will take up 100% CPU

#### Steps to reproduce
Tested with Raspberry Pi Zero W and Hyperion Alpha6
grab hyperion deb-file with "wget <link-to-alpha6-deb-file>"
then "sudo dpkg -i <alpha-6-deb-file>"

#### What is expected?
Raspberry Pi to run normally without any noticable load 

#### What is actually happening?
Rpi becomes unresponsive due to high CPU load from hyperiond
This behaviour doesn't seem to happen with alpha7, but alpha7 has some issues which I don't know are related to this.

**Comment by Paulchen-Panther** [comment] 2020-08-18 10:19
Tested with Raspberry Pi Zero W and Hyperion **_Alpha6_**

Are you serious?

**Comment by T-IOOO** [comment] 2020-08-18 10:26
Please don't be sarcastic! Yes I am serious. What part is it you dont't understand??

**Comment by tpmodding** [comment] 2020-08-18 10:41
The part that we war on alpha7 and not on alpah6, so everything under alpha7 is not relevant....

if you have problems with alpha7, then we would be glad if you can report your problem, BUT please check befor if the problem is already reported...

i will close this one, thank you

**Closed by tpmodding** 2020-08-18 10:41 UTC
Labels: Waiting For Review

**Comment by T-IOOO** [comment] 2020-08-18 10:48
Well, unfortunately alpha7 have bugs with effects and RGB-colors, which was working fine with alpha6.
I am aware that alpha7 is the latest topic concerning bug reports but that's also why I mentioned in my first post - that alpha7 don't have this issue. I just wanted to bring this up so that we can pin point where the issue resides.

**Comment by tpmodding** [comment] 2020-08-18 10:50
do you know how to compile? could you test the current master, there some issues already fixed

**Comment by T-IOOO** [comment] 2020-08-18 10:56
> do you know how to compile? could you test the current master, there some issues already fixed

I think I do, but it takes forever with my Pi0. I prefer waiting for the next release.

**Comment by tpmodding** [comment] 2020-08-18 10:57
just let it compile...you dont have to watch for it, you want help, we want feedback, so lets go
