### ISSUE TITLE
No image from Internal grabber on Raspberry Pi 4 (Bullseye)

### ISSUE THREAD

**Issue by ReWiG** [hyperion-project/hyperion.ng#1397] opened 2021-12-19 11:01 UTC
- [x] I confirm that this is an issue rather than a question.

## Bug report

I am using my Raspberry PI 4 to watch videos in Kodi player, I want to use Ambilight. I installed the latest version of hyperion.ng and run it, set it up and all the effects work, but not the screen capture. I used the only choice in the capture hardware settings "framebuffer", the "FB0" input. If I click on the live video, I only see a black screen. There are no errors in the logs either.

Here are my specs:

Raspberry Pi 4 2 GB

The Latest Raspberry OS version (Bullseye)

The Latest Hyperion.NG version

The Latest Kodi version (19.3)

apa102 LEDS

Do you guys have any ideas why it does not work?

#### System

Hyperion Server: 
- Build:           (HEAD detached at 2.0.12) (GitHub-dc6aa4d/df14958-1637501177)
- Build time:      Nov 21 2021 17:25:12
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.12
- UI Lang:         en (BrowserLang: ru-RU)
- UI Access:       expert
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Config path:     /home/pi/.hyperion
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 11 (bullseye)
- Architecture:   arm
- CPU Model:      ARMv7 Processor rev 3 (v7l)
- CPU Type:       Raspberry Pi 4 Model B Rev 1.1
- CPU Revision:   b03111
- CPU Hardware:   BCM2711
- Kernel:         linux (5.10.83-v7l+ (WS: 32))
- Root/Admin:     false
- Qt Version:     5.15.2
- Python Version: 3.9.2
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0

**Comment by Chaphasilor** [comment] 2022-01-06 18:24
duplicate of #983

it's not supported yet...

**Comment by Lord-Grey** [comment] 2022-02-06 16:17
Closing, as duplicate....

**Closed by Lord-Grey** 2022-02-06 16:17 UTC
