### ISSUE TITLE
Backlight threshold stays on when TV off

### ISSUE THREAD

**Issue by T-IOOO** [hyperion-project/hyperion.ng#982] opened 2020-08-29 13:56 UTC
- [x] I confirm that this is an issue rather than a question.

## Bug report
For example, When backlight threshold is 20% (or any value over 0), when I shit off my TV the backlight threshold stays on.

#### Steps to reproduce
Tested with Rpi0 W and with APA102.

#### What is expected?
When TV is OFF the backlight threshold should also be off.

#### What is actually happening?
Lights stays on. I have tested different values in signal detection and put CEC-detection on and off.

I have a splitter in my setup.

#### System

Hyperion Server: 
- Build:       master (GitHub-f719f0b2/838092e2-1597257777)
- Build time:  Aug 19 2020 09:05:55
- Git Remote:  https://github.com/hyperion-project/hyperion.ng.git
- Version:     2.0.0-alpha.7
- UI Lang:     sv (BrowserLang: sv)
- UI Access:   expert
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: Raspbian GNU/Linux 10 (buster)
- Arch:         arm
- Kernel:       linux (5.4.51+ (WS: 32))
- Browser:      Mozilla/5.0 (iPhone; CPU iPhone OS 13_6_1 like

**Comment by m-seker** [comment] 2020-08-29 15:42
Logs please

**Comment by Lord-Grey** [comment] 2020-08-29 16:03
@m-seker , @Paulchen-Panther Depending on the outcome of the investigation, I would suggest combining this with the new capabilities which will be introduced via #960. 
In case a "switch-off" scenario is detected this can signal the switch-off of the device(s).
A device will be switched-off correctly according its specifics. There is no need to do changes on image calculations.
This would be true decoupling.

**Comment by Lord-Grey** [comment] 2021-07-18 16:42
Can you re-test with alpha10 and report back please, if the issue is still present?

**Closed by Lord-Grey** 2021-07-18 16:42 UTC
