### ISSUE TITLE
device 'lightpack' signals error: 'No working Lightpack device found with serial ******

### ISSUE THREAD

**Issue by gamer06** [hyperion-project/hyperion.ng#1484] opened 2022-07-04 22:35 UTC
- [x] I confirm that this is an issue rather than a question.

## Bug report

Hello everybody.

I downloaded the latest version for my raspberry pi A and however when I choose "lightpack" mode the following message appears:
`2022-07-04T22:30:20.159Z [LEDDEVICE|First LED Hardware instance] (ERROR) Device disabled, device 'lightpack' signals error: 'No working Lightpack device found with serial 95330313939351B0C1A1'`

![image](https://user-images.githubusercontent.com/23462360/177222328-7d5877e5-393c-4b50-b0b4-5ce11f409265.png)

![image](https://user-images.githubusercontent.com/23462360/177222297-40ddecdc-0e77-4605-b945-e01714e7c163.png)

Thanks!!!

#### System

Hyperion Server:
- Build:             (HEAD detached at 2.0.13) (GitHub-dfd9438/5dc696b-1653218333)
- Build time:        May 22 2022 12:55:01
- Git Remote:        https://github.com/hyperion-project/hyperion.ng
- Version:           2.0.13
- UI Lang:           en (BrowserLang: pt-PT)
- UI Access:         expert
- Avail Screen Cap.: dispmanx,framebuffer,qt
- Avail Video  Cap.: v4l2
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       /home/pi/.hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      HyperBian GNU/Linux 11 (bullseye)
- Architecture:      arm
- CPU Model:         ARMv6-compatible processor rev 7 (v6l)
- CPU Type:          Raspberry Pi Model B Rev 2
- CPU Revision:      000d
- CPU Hardware:      BCM2835
- Kernel:            linux (5.15.32+ (WS: 32))
- Root/Admin:        false
- Qt Version:        5.15.2
- Python Version:    3.9.2
- Browser:           Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Saf

**Comment by Lord-Grey** [comment] 2022-07-05 06:33
@gamer06 Would you mind proving additional details for investigation, please?

a) Please put Hyperion in Debug logging mode (via UI: System->Log).
b) Configure the Lightpack device without the serial number and save the configuration
c) Share the Hyperion log output

**Comment by gamer06** [comment] 2022-07-05 06:39
> @gamer06 Would you mind proving additional details for investigation, please?
> 
> a) Please put Hyperion in Debug logging mode (via UI: System->Log). b) Configure the Lightpack device without the serial number and save the configuration c) Share the Hyperion log output

Thanks for the brief reply.
Then I changed it to debug logging mode and device without serial number.
Here is the log:

`2022-07-04T22:23:23.891Z [LEDDEVICE|First LED Hardware instance] (ERROR) Device disabled, device 'lightpack' signals error: 'No working Lightpack device found with serial 95330313939351B0C1A1'
2022-07-04T22:25:13.390Z [LEDDEVICE|First LED Hardware instance] (ERROR) Device disabled, device 'lightpack' signals error: 'No working Lightpack device found with serial 1d50:6022'
2022-07-04T22:30:20.159Z [LEDDEVICE|First LED Hardware instance] (ERROR) Device disabled, device 'lightpack' signals error: 'No working Lightpack device found with serial 95330313939351B0C1A1'
2022-07-05T06:36:43.481Z [WEBSOCKET] (DEBUG) (WebSocketClient.cpp:215:sendClose()) Send close to ::ffff:192.168.1.161: 1000 
2022-07-05T06:36:47.139Z [WEBSOCKET] (DEBUG) (WebSocketClient.cpp:30:WebSocketClient()) New connection from ::ffff:192.168.1.161
2022-07-05T06:36:47.952Z [WEBSOCKET] (DEBUG) (JsonAPI.cpp:129:handleInstanceSwitch()) Client '::ffff:192.168.1.161' switch to Hyperion instance 0
2022-07-05T06:36:48.530Z [WEBSOCKET] (DEBUG) (JsonAPI.cpp:1184:handleLoggingCommand()) log streaming activated for client ::ffff:192.168.1.161
2022-07-05T06:37:01.006Z [LEDDEVICE|First LED Hardware instance] (DEBUG) (LedDevice.cpp:99:stop()) Stop device
2022-07-05T06:37:01.015Z [LEDDEVICE|First LED Hardware instance] (DEBUG) (LedDevice.cpp:189:disable()) Disable device lightpack'
2022-07-05T06:37:01.032Z [LEDDEVICE|First LED Hardware instance] (INFO)  Stopped LedDevice 'lightpack'
2022-07-05T06:37:01.049Z [LEDDEVICE|First LED Hardware instance] (INFO) Start LedDevice 'lightpack'.
2022-07-05T06:37:01.058Z [LEDDEVICE|First LED Hardware instance] (DEBUG) (LedDevice.cpp:210:init()) deviceConfig: [{"autoStart":true,"colorOrder":"rgb","currentLedCount":1,"enableAttempts":6,"enableAttemptsInterval":15,"hardwareLedCount":1,"latchTime":11,"rewriteTime":1000,"serial":"","type":"lightpack"}]
2022-07-05T06:37:01.070Z [LEDDEVICE|First LED Hardware instance] (DEBUG) (LedDevice.cpp:563:setLedCount()) LedCount set to 1
2022-07-05T06:37:01.079Z [LEDDEVICE|First LED Hardware instance] (DEBUG) (LedDevice.cpp:569:setColorOrder()) ColorOrder set to RGB
2022-07-05T06:37:01.096Z [LEDDEVICE|First LED Hardware instance] (DEBUG) (LedDevice.cpp:576:setLatchTime()) LatchTime set to 11ms
2022-07-05T06:37:01.101Z [LEDDEVICE|First LED Hardware instance] (DEBUG) (LedDevice.cpp:600:setRewriteTime()) Refresh interval = 1000ms
2022-07-05T06:37:01.108Z [LEDDEVICE|First LED Hardware instance] (DEBUG) (LedDevice.cpp:244:startRefreshTimer()) Device is not ready to start a refresh timer
2022-07-05T06:37:01.113Z [LEDDEVICE|First LED Hardware instance] (DEBUG) (LedDevice.cpp:582:setAutoStart()) AutoStart enabled
2022-07-05T06:37:01.119Z [LEDDEVICE|First LED Hardware instance] (DEBUG) (LedDevice.cpp:619:setEnableAttempts()) Max enable retries: 6, enable retry interval = 15s
2022-07-05T06:37:01.296Z [WEBSOCKET] (DEBUG) (WebSocketClient.cpp:215:sendClose()) Send close to ::ffff:192.168.1.161: 1000 
2022-07-05T06:37:01.309Z [LEDDEVICE|First LED Hardware instance] (DEBUG) (LedDeviceLightpack.cpp:83:init()) USB context initialized
2022-07-05T06:37:01.316Z [LEDDEVICE|First LED Hardware instance] (INFO) Found a Lightpack device. Retrieving more information...
2022-07-05T06:37:01.322Z [LEDDEVICE|First LED Hardware instance] (DEBUG) (LedDeviceLightpack.cpp:205:searchDevice()) vendorIdentifier : 0x1d50
2022-07-05T06:37:01.329Z [LEDDEVICE|First LED Hardware instance] (DEBUG) (LedDeviceLightpack.cpp:206:searchDevice()) productIdentifier: 0x6022
2022-07-05T06:37:01.336Z [LEDDEVICE|First LED Hardware instance] (DEBUG) (LedDeviceLightpack.cpp:207:searchDevice()) release_number   : 0x1
2022-07-05T06:37:01.343Z [LEDDEVICE|First LED Hardware instance] (DEBUG) (LedDeviceLightpack.cpp:208:searchDevice()) manufacturer     : 
2022-07-05T06:37:01.353Z [LEDDEVICE|First LED Hardware instance] (DEBUG) (LedDeviceLightpack.cpp:216:searchDevice()) Lightpack device found: bus=1 address=5 serial=
2022-07-05T06:37:01.359Z [LEDDEVICE|First LED Hardware instance] (ERROR) unable to open device(-3): LIBUSB_ERROR_ACCESS
2022-07-05T06:37:01.370Z [LEDDEVICE|First LED Hardware instance] (WARNING) Unable to open Lightpack device. Searching for other device
2022-07-05T06:37:01.376Z [LEDDEVICE|First LED Hardware instance] (ERROR) Device disabled, device 'lightpack' signals error: 'No working Lightpack devices were found'
2022-07-05T06:37:03.562Z [WEBSOCKET] (DEBUG) (WebSocketClient.cpp:30:WebSocketClient()) New connection from ::ffff:192.168.1.161
2022-07-05T06:37:04.407Z [WEBSOCKET] (DEBUG) (JsonAPI.cpp:129:handleInstanceSwitch()) Client '::ffff:192.168.1.161' switch to Hyperion instance 0
2022-07-05T06:37:09.449Z [WEBSOCKET] (DEBUG) (JsonAPI.cpp:1184:handleLoggingCommand()) log streaming activated for client ::ffff:192.168.1.161`

**Comment by Lord-Grey** [comment] 2022-07-05 06:50
The problem is that the user running Hyperion has not access rights to the device.

`T06:37:01.359Z [LEDDEVICE|First LED Hardware instance] (ERROR) unable to open device(-3): LIBUSB_ERROR_ACCESS`

This is not a Hyperion problem, but needs to be fixed on OS level.

see here https://github.com/hyperion-project/hyperion.ng/issues/1332#issuecomment-923062729

**Closed by Lord-Grey** 2022-07-05 06:50 UTC
Labels: Waiting for Input
