### ISSUE TITLE
Hyperiond memory leak on RPi3B+Arduino

### ISSUE THREAD

**Issue by fragande** [hyperion-project/hyperion.ng#722] opened 2020-03-10 22:13 UTC
- [x] I confirm that this is an issue rather than a question.

## Bug report
On my setup hyperiond (daemon?) memory usage starts out very low and then gradually grows until system crashes/grinds to a halt due to running out of memory. My setup is a RPi3B running LibreElec, an Arduino Nano and WS2812B LEDs. I had the same issue with old Hyperion.

#### Steps to reproduce
Simply leave hyperion-ng running with normal usage, changing effects a few times a day (from HDMI when playing media to mood lightning effects etc.). As of writing this the system has been up for 6 days and hyperiond memory usage is at about ~600MB. 

#### What is expected?
That hyperiond memory usage would stay about the same over time.

#### What is actually happening?
hyperiond memory usage grows endlessly until system crash.

#### System

```
Hyperion Server: 
- Build:       (HEAD detached at bec6c495) (brindosch-0ff09987/bec6c495-1583074045)
- Build time:  Mar  1 2020 15:18:20
- Git Remote:  https://github.com/hyperion-project/hyperion.ng
- Version:     2.0.0-alpha.3
- UI Lang:     auto (BrowserLang: sv-SE)
- UI Access:   expert
- Avail Capt:  dispmanx,v4l2,framebuffer,qt

Hyperion Server OS: 
- Distribution: LibreELEC (official): 9.2.0
- Arch:         arm
- Kernel:       linux (4.19.83 (WS: 32))
- Browser:      Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0 
```

**Comment by T-IOOO** [comment] 2020-03-11 21:44
I think I also have issues with memory leaks. Hyperiond using constantly 100% cpu. The thing is when I disable the grabber in webui the cpu drops to what i consider normal usage. Is anyone here having this issue? My setup is rpi0w, APA102, EasyCap (macrosilicon) grabber

**Comment by brindosch** [comment] 2020-03-12 17:41
Hello, can you please reduce the capture interval and report back how it _behaves_? If the system load is high enough i expect a growing queue of internal tasks

**Comment by fragande** [comment] 2020-03-12 18:27
> 
> 
> Hello, can you please reduce the capture interval and report back how it _behaves_? If the system load is high enough i expect a growing queue of internal tasks

Capture interval is the same as capture frequency I assume? I have lowered it to 5 Hz from the standard 10, will report back. But I'm almost certain this happens even when there is no capture, i.e. only running and switching between static lightning/mood lightning effects etc. (I have this automated with about four "scene" switches per day).

I don't have the issue of high CPU usage as @T-IOOO reports. For me CPU usage is the same (~2-5%) on fresh boot and when hyperiond is using ~700-800MB RAM after about 8-9 days.

**Comment by fragande** [comment] 2020-03-19 04:18
After six days RAM usage is at ~50% so about 500MB. Maybe a slight decrease changing to 5 Hz, last time usage was at ~600MB after six days with 10 Hz.

**Comment by tpmodding** [comment] 2020-06-03 16:44
@Lord-Grey

**Comment by Lord-Grey** [comment] 2020-06-03 19:09
@tpmodding Assumption is that it caused by the EffectEngine given that memory allocated is not properly released. Requires further investigation.

**Comment by m-seker** [comment] 2020-07-05 00:49
All,

Can you try after https://github.com/hyperion-project/hyperion.ng/pull/863 is merged ? It fixes a possible recurring leak.

**Closed** 2020-07-12 07:22 UTC
Labels: bug, needs investigation

**Comment by fragande** [comment] 2020-10-14 19:55
> 
> 
> All,
> 
> Can you try after #863 is merged ? It fixes a possible recurring leak.

Sorry for the late reply. I'm still having this issue on 2.0.0-alpha.8 unfortunately.
