### ISSUE TITLE
No video grabbing without network

### ISSUE THREAD

**Issue by direk** [hyperion-project/hyperion.ng#813] opened 2020-05-29 13:59 UTC
- [x] I confirm that this is an issue rather than a question.

## Bug report
When I start raspberry pi with usb grabber and no network connection LEDs are showing "welcome effect" only. To make device work as ambilight I have to connect network (either wireless or ethernet cable) and open hyperion web config panel.

#### Steps to reproduce
- Flash newest raspbian (console only)
- Install Hyperion 2.0.0-alpha.6
- Run without network (either cable unplugged or wifi not confitured)

#### What is expected?
Welcome effect is shown on LEDs and then LEDs should represent colours from grabbing interface.

#### What is actually happening?
Welcome effect is shown on LEDs (static rainbow in my case), but no video processing occurs until I connect network cable and visit config webpage.

#### System

Tested on Raspberry Pi 1 (with ethernet cable and wifi dongle) and Raspberry Pi zero w.
LEDs are ws2812b on spi port.

**Comment by tpmodding** [comment] 2020-06-17 19:39
which grabber do you use? internal or usb?

**Comment by Lord-Grey** [comment] 2021-07-18 16:49
Can you re-test with alpha10 and report back please, if the issue is still present?

**Comment by Lord-Grey** [comment] 2021-08-04 19:28
Closing, as no feedback provided. Can be reopened, if needed.

**Closed by Lord-Grey** 2021-08-04 19:28 UTC
Labels: needs investigation
