### ISSUE TITLE
web effect configurator saving config issues

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion.ng#324] opened 2016-12-09 13:16 UTC
1) if you have multiple effect paths in your config, it tries to write to the 1st one only

2) when this fails (maybe the dir doesnt exist) the web UI claims successs:
Effect created!
The effect Candle90 has been created successfully!

**Comment by brindosch** [comment] 2016-12-09 13:27
Yes, i assume always it works. This should be reworked to use callbacks. The issue is now, how could i catch accordingly the event success (as the websocket itself reports all issues)
@b1rdhous3 @redPanther

**Comment by redPanther** [comment] 2016-12-09 22:47
> 1. if you have multiple effect paths in your config, it tries to write to the 1st one only

we should separate the paths:
custom_path -  only one entry. This is for all custom effects (new effects go here)
additional_paths - additional paths, readonly. This should be an "advanced" setting

> catch event ...

The websocket reports if effect was created or not. This should be catched by effect configurator.
effectsconfigurator.js ~ line 144

change this
```
	$('#btn_write').off().on('click',function() {
		if(validateEditor())
		{
			requestWriteEffect(effectName,effectPy,JSON.stringify(effects_editor.getValue()));
			showInfoDialog('success', $.i18n('infoDialog_effconf_created_title'), $.i18n('infoDialog_effconf_created_text', effectName));
		}
	});
```
into this

```
	$('#btn_write').off().on('click',function() {
		if(validateEditor())
		{
			$(hyperion).one("create-effect", function(event) {
			if (event.response.success) {
				showInfoDialog('success', $.i18n('infoDialog_effconf_created_title'), $.i18n('infoDialog_effconf_created_text', effectName));
			} else {
				showInfoDialog('error', $.i18n('infoDialog_effconf_created_failed_title'), $.i18n('infoDialog_effconf_created_failed_text', event.response.error));
			}
	        	});
			requestWriteEffect(effectName,effectPy,JSON.stringify(effects_editor.getValue()));

		}
	});
```

just a quick coding with trying ... but this is the general pattern for dealing with response

**Comment by brindosch** [comment] 2016-12-09 23:04
Yes this was in my mind! Wasn't sure how to deal with the hyperion class :)
But we get now a race between websocket::onerror modal and this modal? Will do some tests :)

**Comment by redPanther** [comment] 2016-12-09 23:09
Keep attention to 'on' if you instsll the handler it will be active as long as your session lives. If possible use 'one' that is only one time called when event occurs.

To avoid multiple handlers for same event you will see this command: .off().on(....) often on our code.

**Comment by brindosch** [comment] 2016-12-09 23:26
Good to know thank you.
Sadly the event callback is never triggered.
I noticed something before on the logging page. request logging and schema for editor didn't worked. We need more ToDos, do we? Here we are! :)

**Comment by brindosch** [comment] 2017-01-23 11:53
//fixed with next update

**Closed by brindosch** 2017-01-23 11:53 UTC
Labels: Backlog
