### ISSUE TITLE
when Hyperion is turned off, the brightness of the LED does not returndoes not return brightness

### ISSUE THREAD

**Issue by DivanX10** [hyperion-project/hyperion.ng#1393] opened 2021-12-08 15:48 UTC
- [x] I confirm that this is an issue rather than a question.

## Bug report
When I turn off the LED device (LED) for the first time, the brightness remains on the WLED returns to the same level as it was before hyperion turned on, and if I turn on hyperion again with WLED turned on and turn off hyperion, then the brightness of the WLED will be 255. I am currently fixing the problem with the help of Home Assistant

#### What is expected?
when you turn off the hyperion through the LED device (LED), the brightness level of the LED will return as it was before turning on the hyperion

#### System

Hyperion Server OS: 
- Distribution:   Windows 10 Version 2009
- Architecture:   x86_64
- Kernel:         winnt (10.0.19042 (WS: 64))
- Root/Admin:     false
- Qt Version:     5.15.0
- Python Version: 3.10.0

**Comment by Lord-Grey** [comment] 2021-12-08 16:27
How have you configured the WLED device?

![image](https://user-images.githubusercontent.com/48840279/145245128-b0dfaf81-4cc3-4a41-ae1b-a4285b0defd7.png)

Are there any communication/network failures in the log?

**Comment by DivanX10** [comment] 2021-12-08 22:17
Yes, it's all on for me. I don't notice dumps at WLED since everything works fine, management + frame capture works fine. There are no freezes.

<details>
  <summary><b>Screenshot</b></summary>

![image](https://user-images.githubusercontent.com/64090632/145292980-622ec946-e8d0-4f70-9e86-79c09974096c.png)
</details>

<details>
  <summary><b>Log output</b></summary>
Hyperion System Summary Report (WLED Monitor), Reported instance: unknown

< ----- System information -------------------- >
Hyperion Server: 
- Build:           (HEAD detached at df149583) (GitHub-dc6aa4dd/df149583-1637501177)
- Build time:      Nov 21 2021 16:50:38
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.12
- UI Lang:         ru (BrowserLang: ru-RU)
- UI Access:       advanced
- Avail Capt:      v4l2,qt,dx
- Config path:     C:/Users/Home/.hyperion
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Windows 10 Version 2009
- Architecture:   x86_64
- Kernel:         winnt (10.0.19042 (WS: 64))
- Root/Admin:     false
- Qt Version:     5.15.0
- Python Version: 3.10.0
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 OPR/81.0.4196.60 (Edition Yx 05)

< ----- Configured Instances ------------------ >
0: WLED Livingroom Monitor Running: true

< ----- This instance's priorities ------------ >
100:  VISIBLE! (GRABBER) Owner: Qt
priorities_autoselect: true

< ----- This instance components' status ------->
ALL - true
SMOOTHING - false
BLACKBORDER - true
FORWARDER - false
BOBLIGHTSERVER - false
GRABBER - true
V4L - false
LEDDEVICE - false

< ----- This instance's configuration --------- >
{"backgroundEffect":{"color":[255,138,0],"effect":"Warm mood blobs","enable":false,"type":"effect"},"blackborderdetector":{"blurRemoveCnt":1,"borderFrameCnt":50,"enable":true,"maxInconsistentCnt":10,"mode":"default","threshold":5,"unknownFrameCnt":600},"boblightServer":{"enable":false,"port":19333,"priority":128},"color":{"channelAdjustment":[{"backlightColored":false,"backlightThreshold":0,"blue":[0,0,255],"brightness":100,"brightnessCompensation":100,"cyan":[0,255,255],"gammaBlue":2.2,"gammaGreen":2.2,"gammaRed":2.2,"green":[0,255,0],"id":"default","leds":"*","magenta":[255,0,255],"red":[255,0,0],"white":[255,255,255],"yellow":[255,255,0]}],"imageToLedMappingType":"multicolor_mean"},"device":{"brightness":255,"colorOrder":"rgb","hardwareLedCount":93,"host":"192.168.1.207","hostList":"NONE","latchTime":0,"overwriteBrightness":true,"overwriteSync":true,"restoreOriginalState":true,"type":"wled"},"effects":{"disable":[""],"paths":["$ROOT/custom-effects"]},"flatbufServer":{"enable":true,"port":19400,"timeout":5},"foregroundEffect":{"color":[0,0,255],"duration_ms":3000,"effect":"Rainbow swirl fast","enable":true,"type":"effect"},"forwarder":{"enable":false,"flat":[],"json":[]},"framegrabber":{"available_devices":"QT","cropBottom":0,"cropLeft":0,"cropRight":0,"cropTop":0,"device":"qt","device_inputs":"0","enable":true,"fps":25,"framerates":"25","height":1080,"input":0,"pixelDecimation":8,"resolutions":"0","width":1920},"general":{"configVersion":"2.0.12","name":"WLED Monitor","previousVersion":"2.0.12","showOptHelp":true,"watchedVersionBranch":"Stable"},"grabberV4L2":{"blueSignalThreshold":0,"cecDetection":false,"cropBottom":0,"cropLeft":0,"cropRight":0,"cropTop":0,"device":"none","enable":false,"encoding":"NO_CHANGE","flip":"NO_CHANGE","fps":15,"fpsSoftwareDecimation":0,"greenSignalThreshold":100,"hardware_brightness":0,"hardware_contrast":0,"hardware_hue":0,"hardware_saturation":0,"height":0,"input":0,"noSignalCounterThreshold":200,"redSignalThreshold":0,"sDHOffsetMax":0.46,"sDHOffsetMin":0.4,"sDVOffsetMax":0.9,"sDVOffsetMin":0.1,"signalDetection":false,"sizeDecimation":8,"width":0},"instCapture":{"systemEnable":true,"systemGrabberDevice":"QT","systemPriority":100,"v4lEnable":false,"v4lGrabberDevice":"NONE","v4lPriority":240},"jsonServer":{"port":19444},"ledConfig":{"classic":{"bottom":27,"edgegap":0,"glength":0,"gpos":0,"hdepth":8,"left":18,"overlap":0,"pblh":0,"pblv":100,"pbrh":100,"pbrv":100,"position":54,"ptlh":0,"ptlv":0,"ptrh":100,"ptrv":0,"reverse":false,"right":18,"top":30,"vdepth":5},"ledBlacklist":[],"matrix":{"cabling":"snake","ledshoriz":1,"ledsvert":1,"start":"top-left"}},"leds":[{"hmax":0.7778,"hmin":0.7407,"vmax":1,"vmin":0.92},{"hmax":0.7407,"hmin":0.7037,"vmax":1,"vmin":0.92},{"hmax":0.7037,"hmin":0.6667,"vmax":1,"vmin":0.92},{"hmax":0.6667,"hmin":0.6296,"vmax":1,"vmin":0.92},{"hmax":0.6296,"hmin":0.5926,"vmax":1,"vmin":0.92},{"hmax":0.5926,"hmin":0.5556,"vmax":1,"vmin":0.92},{"hmax":0.5556,"hmin":0.5185,"vmax":1,"vmin":0.92},{"hmax":0.5185,"hmin":0.4815,"vmax":1,"vmin":0.92},{"hmax":0.4815,"hmin":0.4444,"vmax":1,"vmin":0.92},{"hmax":0.4444,"hmin":0.4074,"vmax":1,"vmin":0.92},{"hmax":0.4074,"hmin":0.3704,"vmax":1,"vmin":0.92},{"hmax":0.3704,"hmin":0.3333,"vmax":1,"vmin":0.92},{"hmax":0.3333,"hmin":0.2963,"vmax":1,"vmin":0.92},{"hmax":0.2963,"hmin":0.2593,"vmax":1,"vmin":0.92},{"hmax":0.2593,"hmin":0.2222,"vmax":1,"vmin":0.92},{"hmax":0.2222,"hmin":0.1852,"vmax":1,"vmin":0.92},{"hmax":0.1852,"hmin":0.1481,"vmax":1,"vmin":0.92},{"hmax":0.1481,"hmin":0.1111,"vmax":1,"vmin":0.92},{"hmax":0.1111,"hmin":0.0741,"vmax":1,"vmin":0.92},{"hmax":0.0741,"hmin":0.037,"vmax":1,"vmin":0.92},{"hmax":0.037,"hmin":0,"vmax":1,"vmin":0.92},{"hmax":0.05,"hmin":0,"vmax":1,"vmin":0.9444},{"hmax":0.05,"hmin":0,"vmax":0.9444,"vmin":0.8889},{"hmax":0.05,"hmin":0,"vmax":0.8889,"vmin":0.8333},{"hmax":0.05,"hmin":0,"vmax":0.8333,"vmin":0.7778},{"hmax":0.05,"hmin":0,"vmax":0.7778,"vmin":0.7222},{"hmax":0.05,"hmin":0,"vmax":0.7222,"vmin":0.6667},{"hmax":0.05,"hmin":0,"vmax":0.6667,"vmin":0.6111},{"hmax":0.05,"hmin":0,"vmax":0.6111,"vmin":0.5556},{"hmax":0.05,"hmin":0,"vmax":0.5556,"vmin":0.5},{"hmax":0.05,"hmin":0,"vmax":0.5,"vmin":0.4444},{"hmax":0.05,"hmin":0,"vmax":0.4444,"vmin":0.3889},{"hmax":0.05,"hmin":0,"vmax":0.3889,"vmin":0.3333},{"hmax":0.05,"hmin":0,"vmax":0.3333,"vmin":0.2778},{"hmax":0.05,"hmin":0,"vmax":0.2778,"vmin":0.2222},{"hmax":0.05,"hmin":0,"vmax":0.2222,"vmin":0.1667},{"hmax":0.05,"hmin":0,"vmax":0.1667,"vmin":0.1111},{"hmax":0.05,"hmin":0,"vmax":0.1111,"vmin":0.0556},{"hmax":0.05,"hmin":0,"vmax":0.0556,"vmin":0},{"hmax":0.0333,"hmin":0,"vmax":0.08,"vmin":0},{"hmax":0.0667,"hmin":0.0333,"vmax":0.08,"vmin":0},{"hmax":0.1,"hmin":0.0667,"vmax":0.08,"vmin":0},{"hmax":0.1333,"hmin":0.1,"vmax":0.08,"vmin":0},{"hmax":0.1667,"hmin":0.1333,"vmax":0.08,"vmin":0},{"hmax":0.2,"hmin":0.1667,"vmax":0.08,"vmin":0},{"hmax":0.2333,"hmin":0.2,"vmax":0.08,"vmin":0},{"hmax":0.2667,"hmin":0.2333,"vmax":0.08,"vmin":0},{"hmax":0.3,"hmin":0.2667,"vmax":0.08,"vmin":0},{"hmax":0.3333,"hmin":0.3,"vmax":0.08,"vmin":0},{"hmax":0.3667,"hmin":0.3333,"vmax":0.08,"vmin":0},{"hmax":0.4,"hmin":0.3667,"vmax":0.08,"vmin":0},{"hmax":0.4333,"hmin":0.4,"vmax":0.08,"vmin":0},{"hmax":0.4667,"hmin":0.4333,"vmax":0.08,"vmin":0},{"hmax":0.5,"hmin":0.4667,"vmax":0.08,"vmin":0},{"hmax":0.5333,"hmin":0.5,"vmax":0.08,"vmin":0},{"hmax":0.5667,"hmin":0.5333,"vmax":0.08,"vmin":0},{"hmax":0.6,"hmin":0.5667,"vmax":0.08,"vmin":0},{"hmax":0.6333,"hmin":0.6,"vmax":0.08,"vmin":0},{"hmax":0.6667,"hmin":0.6333,"vmax":0.08,"vmin":0},{"hmax":0.7,"hmin":0.6667,"vmax":0.08,"vmin":0},{"hmax":0.7333,"hmin":0.7,"vmax":0.08,"vmin":0},{"hmax":0.7667,"hmin":0.7333,"vmax":0.08,"vmin":0},{"hmax":0.8,"hmin":0.7667,"vmax":0.08,"vmin":0},{"hmax":0.8333,"hmin":0.8,"vmax":0.08,"vmin":0},{"hmax":0.8667,"hmin":0.8333,"vmax":0.08,"vmin":0},{"hmax":0.9,"hmin":0.8667,"vmax":0.08,"vmin":0},{"hmax":0.9333,"hmin":0.9,"vmax":0.08,"vmin":0},{"hmax":0.9667,"hmin":0.9333,"vmax":0.08,"vmin":0},{"hmax":1,"hmin":0.9667,"vmax":0.08,"vmin":0},{"hmax":1,"hmin":0.95,"vmax":0.0556,"vmin":0},{"hmax":1,"hmin":0.95,"vmax":0.1111,"vmin":0.0556},{"hmax":1,"hmin":0.95,"vmax":0.1667,"vmin":0.1111},{"hmax":1,"hmin":0.95,"vmax":0.2222,"vmin":0.1667},{"hmax":1,"hmin":0.95,"vmax":0.2778,"vmin":0.2222},{"hmax":1,"hmin":0.95,"vmax":0.3333,"vmin":0.2778},{"hmax":1,"hmin":0.95,"vmax":0.3889,"vmin":0.3333},{"hmax":1,"hmin":0.95,"vmax":0.4444,"vmin":0.3889},{"hmax":1,"hmin":0.95,"vmax":0.5,"vmin":0.4444},{"hmax":1,"hmin":0.95,"vmax":0.5556,"vmin":0.5},{"hmax":1,"hmin":0.95,"vmax":0.6111,"vmin":0.5556},{"hmax":1,"hmin":0.95,"vmax":0.6667,"vmin":0.6111},{"hmax":1,"hmin":0.95,"vmax":0.7222,"vmin":0.6667},{"hmax":1,"hmin":0.95,"vmax":0.7778,"vmin":0.7222},{"hmax":1,"hmin":0.95,"vmax":0.8333,"vmin":0.7778},{"hmax":1,"hmin":0.95,"vmax":0.8889,"vmin":0.8333},{"hmax":1,"hmin":0.95,"vmax":0.9444,"vmin":0.8889},{"hmax":1,"hmin":0.95,"vmax":1,"vmin":0.9444},{"hmax":1,"hmin":0.963,"vmax":1,"vmin":0.92},{"hmax":0.963,"hmin":0.9259,"vmax":1,"vmin":0.92},{"hmax":0.9259,"hmin":0.8889,"vmax":1,"vmin":0.92},{"hmax":0.8889,"hmin":0.8519,"vmax":1,"vmin":0.92},{"hmax":0.8519,"hmin":0.8148,"vmax":1,"vmin":0.92},{"hmax":0.8148,"hmin":0.7778,"vmax":1,"vmin":0.92}],"logger":{"level":"debug"},"network":{"apiAuth":true,"internetAccessAPI":false,"ipWhitelist":[],"localAdminAuth":true,"localApiAuth":false,"restirctedInternetAccessAPI":false},"protoServer":{"enable":true,"port":19445,"timeout":5},"smoothing":{"enable":false},"webConfig":{"crtPath":"","document_root":"","keyPassPhrase":"","keyPath":"","port":8090,"sslPort":8092}}

< ----- Current Log --------------------------- >
2021-12-08T22:07:27.695Z [ WEBSOCKET] (DEBUG) (WebSocketClient.cpp:215:WebSocketClient::sendClose()) Send close to ::1: 1000 
2021-12-08T22:07:27.905Z [ WEBSOCKET] (DEBUG) (WebSocketClient.cpp:30:WebSocketClient::WebSocketClient()) New connection from ::1
2021-12-08T22:07:28.110Z [ WEBSOCKET] (DEBUG) (JsonAPI.cpp:122:JsonAPI::handleInstanceSwitch()) Client '::1' switch to Hyperion instance 0
2021-12-08T22:07:28.523Z [ WEBSOCKET] (DEBUG) (JsonAPI.cpp:1090:JsonAPI::handleLoggingCommand()) log streaming activated for client ::1
2021-12-08T22:07:36.187Z [ WEBSOCKET] (DEBUG) (JsonAPI.cpp:1436:JsonAPI::handleLedDeviceCommand()) message: [{"command":"leddevice","ledDeviceType":"wled","subcommand":"discover","tan":851}]
2021-12-08T22:07:36.187Z [ WEBSOCKET] (DEBUG) (JsonAPI.cpp:1460:JsonAPI::handleLedDeviceCommand()) response: [{"devices":[],"ledDeviceType":"wled"}]
2021-12-08T22:07:36.194Z [ WEBSOCKET] (DEBUG) (JsonAPI.cpp:1436:JsonAPI::handleLedDeviceCommand()) message: [{"command":"leddevice","ledDeviceType":"wled","params":{"filter":"info","host":"192.168.1.207"},"subcommand":"getProperties","tan":213}]
2021-12-08T22:07:36.221Z [ WEBSOCKET] (DEBUG) (JsonAPI.cpp:1470:JsonAPI::handleLedDeviceCommand()) response: [{"properties":{"arch":"esp8266","brand":"WLED","core":"2_7_4_7","freeheap":19584,"fs":{"pmt":1638934217,"t":1024,"u":49},"fxcount":118,"ip":"192.168.1.207","leds":{"count":93,"fps":25,"maxpwr":0,"maxseg":16,"pwr":0,"rgbw":false,"wv":false},"lip":"192.168.1.10","live":true,"lm":"Hyperion","lwip":1,"mac":"e8db84ddbe26","maxLedCount":490,"name":"WLED Monitor","ndc":2,"opt":127,"palcount":71,"product":"FOSS","str":false,"udpport":21324,"uptime":123807,"ver":"0.13.0-b5","vid":2111170,"wifi":{"bssid":"50:FF:20:53:B5:91","channel":9,"rssi":-55,"signal":90},"ws":1}}]
2021-12-08T22:07:39.506Z [ LEDDEVICE] (INFO)  Stopped LedDevice 'wled'
2021-12-08T22:07:39.508Z [ LEDDEVICE] (INFO) Start LedDevice 'wled'.
2021-12-08T22:07:39.508Z [ COMPONENTREG] (DEBUG) (ComponentRegister.cpp:41:ComponentRegister::setNewComponentState()) LED device: disabled
2021-12-08T22:07:39.508Z [ LEDDEVICE] (DEBUG) (LedDevice.cpp:148:LedDevice::init()) deviceConfig: [{"brightness":255,"colorOrder":"rgb","currentLedCount":93,"hardwareLedCount":93,"host":"192.168.1.207","hostList":"NONE","latchTime":0,"overwriteBrightness":true,"overwriteSync":true,"restoreOriginalState":true,"type":"wled"}]
2021-12-08T22:07:39.508Z [ LEDDEVICE] (DEBUG) (LedDevice.cpp:414:LedDevice::setLatchTime()) LatchTime updated to 0ms
2021-12-08T22:07:39.508Z [ LEDDEVICE] (DEBUG) (LedDevice.cpp:445:LedDevice::setRewriteTime()) RewriteTime updated to 0ms
2021-12-08T22:07:39.508Z [ LEDDEVICE] (DEBUG) (LedDeviceWled.cpp:80:LedDeviceWled::init()) DeviceType   : wled
2021-12-08T22:07:39.508Z [ LEDDEVICE] (DEBUG) (LedDeviceWled.cpp:81:LedDeviceWled::init()) LedCount     : 93
2021-12-08T22:07:39.509Z [ LEDDEVICE] (DEBUG) (LedDeviceWled.cpp:82:LedDeviceWled::init()) ColorOrder   : rgb
2021-12-08T22:07:39.509Z [ LEDDEVICE] (DEBUG) (LedDeviceWled.cpp:83:LedDeviceWled::init()) LatchTime    : 0
2021-12-08T22:07:39.509Z [ LEDDEVICE] (DEBUG) (LedDeviceWled.cpp:97:LedDeviceWled::init()) RestoreOrigState  : 1
2021-12-08T22:07:39.509Z [ LEDDEVICE] (DEBUG) (LedDeviceWled.cpp:98:LedDeviceWled::init()) Overwrite Sync.   : 1
2021-12-08T22:07:39.509Z [ LEDDEVICE] (DEBUG) (LedDeviceWled.cpp:99:LedDeviceWled::init()) Overwrite Brightn.: 1
2021-12-08T22:07:39.509Z [ LEDDEVICE] (DEBUG) (LedDeviceWled.cpp:100:LedDeviceWled::init()) Set Brightness to : 255
2021-12-08T22:07:39.510Z [ LEDDEVICE] (DEBUG) (LedDevice.cpp:148:LedDevice::init()) deviceConfig: [{"brightness":255,"colorOrder":"rgb","currentLedCount":93,"hardwareLedCount":93,"host":"192.168.1.207","hostList":"NONE","latchTime":0,"overwriteBrightness":true,"overwriteSync":true,"port":19446,"restoreOriginalState":true,"type":"wled"}]
2021-12-08T22:07:39.510Z [ LEDDEVICE] (DEBUG) (LedDevice.cpp:414:LedDevice::setLatchTime()) LatchTime updated to 0ms
2021-12-08T22:07:39.510Z [ LEDDEVICE] (DEBUG) (LedDevice.cpp:445:LedDevice::setRewriteTime()) RewriteTime updated to 0ms
2021-12-08T22:07:39.510Z [ LEDDEVICE] (DEBUG) (ProviderUdp.cpp:43:ProviderUdp::init()) Successfully parsed 192.168.1.207 as an IP-address.
2021-12-08T22:07:39.510Z [ LEDDEVICE] (DEBUG) (ProviderUdp.cpp:73:ProviderUdp::init()) UDP socket will write to 192.168.1.207 port: 19446
2021-12-08T22:07:39.510Z [ LEDDEVICE] (DEBUG) (LedDeviceWled.cpp:131:LedDeviceWled::init()) Hostname/IP  : 192.168.1.207
2021-12-08T22:07:39.510Z [ LEDDEVICE] (DEBUG) (LedDeviceWled.cpp:132:LedDeviceWled::init()) Port         : 19446
2021-12-08T22:07:39.532Z [ LEDDEVICE] (DEBUG) (LedDeviceWled.cpp:211:LedDeviceWled::powerOn()) Disable synchronisation with other WLED devices
2021-12-08T22:07:39.559Z [ COMPONENTREG] (DEBUG) (ComponentRegister.cpp:41:ComponentRegister::setNewComponentState()) LED device: enabled
2021-12-08T22:07:39.589Z [ WEBSOCKET] (DEBUG) (WebSocketClient.cpp:215:WebSocketClient::sendClose()) Send close to ::1: 1000 
2021-12-08T22:07:39.807Z [ WEBSOCKET] (DEBUG) (WebSocketClient.cpp:30:WebSocketClient::WebSocketClient()) New connection from ::1
2021-12-08T22:07:40.024Z [ WEBSOCKET] (DEBUG) (JsonAPI.cpp:122:JsonAPI::handleInstanceSwitch()) Client '::1' switch to Hyperion instance 0
2021-12-08T22:07:40.541Z [ WEBSOCKET] (DEBUG) (JsonAPI.cpp:1436:JsonAPI::handleLedDeviceCommand()) message: [{"command":"leddevice","ledDeviceType":"wled","subcommand":"discover","tan":692}]
2021-12-08T22:07:40.541Z [ WEBSOCKET] (DEBUG) (JsonAPI.cpp:1460:JsonAPI::handleLedDeviceCommand()) response: [{"devices":[],"ledDeviceType":"wled"}]
2021-12-08T22:07:40.547Z [ WEBSOCKET] (DEBUG) (JsonAPI.cpp:1436:JsonAPI::handleLedDeviceCommand()) message: [{"command":"leddevice","ledDeviceType":"wled","params":{"filter":"info","host":"192.168.1.207"},"subcommand":"getProperties","tan":663}]
2021-12-08T22:07:40.572Z [ WEBSOCKET] (DEBUG) (JsonAPI.cpp:1470:JsonAPI::handleLedDeviceCommand()) response: [{"properties":{"arch":"esp8266","brand":"WLED","core":"2_7_4_7","freeheap":19584,"fs":{"pmt":1638934217,"t":1024,"u":49},"fxcount":118,"ip":"192.168.1.207","leds":{"count":93,"fps":29,"maxpwr":0,"maxseg":16,"pwr":0,"rgbw":false,"wv":false},"lip":"192.168.1.10","live":true,"lm":"Hyperion","lwip":1,"mac":"e8db84ddbe26","maxLedCount":490,"name":"WLED Monitor","ndc":2,"opt":127,"palcount":71,"product":"FOSS","str":false,"udpport":21324,"uptime":123811,"ver":"0.13.0-b5","vid":2111170,"wifi":{"bssid":"50:FF:20:53:B5:91","channel":9,"rssi":-54,"signal":92},"ws":1}}]
2021-12-08T22:07:47.378Z [ JSONSERVER] (DEBUG) (JsonServer.cpp:105:JsonServer::newConnection()) New connection from: ::ffff:192.168.1.201
2021-12-08T22:07:49.543Z [ COMPONENTREG] (DEBUG) (ComponentRegister.cpp:41:ComponentRegister::setNewComponentState()) LED device: disabled
2021-12-08T22:07:57.771Z [ COMPONENTREG] (DEBUG) (ComponentRegister.cpp:41:ComponentRegister::setNewComponentState()) LED device: enabled
2021-12-08T22:08:04.741Z [ COMPONENTREG] (DEBUG) (ComponentRegister.cpp:41:ComponentRegister::setNewComponentState()) LED device: disabled
2021-12-08T22:08:20.343Z [ COMPONENTREG] (DEBUG) (ComponentRegister.cpp:41:ComponentRegister::setNewComponentState()) LED device: enabled
2021-12-08T22:08:26.153Z [ COMPONENTREG] (DEBUG) (ComponentRegister.cpp:41:ComponentRegister::setNewComponentState()) LED device: disabled
2021-12-08T22:08:52.564Z [ COMPONENTREG] (DEBUG) (ComponentRegister.cpp:41:ComponentRegister::setNewComponentState()) LED device: enabled
2021-12-08T22:08:56.443Z [ COMPONENTREG] (DEBUG) (ComponentRegister.cpp:41:ComponentRegister::setNewComponentState()) LED device: disabled
2021-12-08T22:09:05.224Z [ COMPONENTREG] (DEBUG) (ComponentRegister.cpp:41:ComponentRegister::setNewComponentState()) LED device: enabled
2021-12-08T22:09:09.179Z [ COMPONENTREG] (DEBUG) (ComponentRegister.cpp:41:ComponentRegister::setNewComponentState()) LED device: disabled
2021-12-08T22:09:20.942Z [ COMPONENTREG] (DEBUG) (ComponentRegister.cpp:41:ComponentRegister::setNewComponentState()) LED device: enabled
2021-12-08T22:09:23.459Z [ COMPONENTREG] (DEBUG) (ComponentRegister.cpp:41:ComponentRegister::setNewComponentState()) LED device: disabled
2021-12-08T22:09:35.315Z [ COMPONENTREG] (DEBUG) (ComponentRegister.cpp:41:ComponentRegister::setNewComponentState()) LED device: enabled
2021-12-08T22:09:39.245Z [ COMPONENTREG] (DEBUG) (ComponentRegister.cpp:41:ComponentRegister::setNewComponentState()) LED device: disabled
2021-12-08T22:09:46.336Z [ COMPONENTREG] (DEBUG) (ComponentRegister.cpp:41:ComponentRegister::setNewComponentState()) LED device: enabled
2021-12-08T22:09:52.314Z [ COMPONENTREG] (DEBUG) (ComponentRegister.cpp:41:ComponentRegister::setNewComponentState()) LED device: disabled
2021-12-08T22:09:58.301Z [ WEBSOCKET] (DEBUG) (JsonAPI.cpp:1090:JsonAPI::handleLoggingCommand()) log streaming activated for client ::1
2021-12-08T22:10:27.919Z [ COMPONENTREG] (DEBUG) (ComponentRegister.cpp:41:ComponentRegister::setNewComponentState()) LED device: enabled
2021-12-08T22:10:31.162Z [ COMPONENTREG] (DEBUG) (ComponentRegister.cpp:41:ComponentRegister::setNewComponentState()) LED device: disabled
2021-12-08T22:10:44.303Z [ COMPONENTREG] (DEBUG) (ComponentRegister.cpp:41:ComponentRegister::setNewComponentState()) LED device: enabled
2021-12-08T22:10:49.088Z [ COMPONENTREG] (DEBUG) (ComponentRegister.cpp:41:ComponentRegister::setNewComponentState()) LED device: disabled
2021-12-08T22:10:55.297Z [ WEBSOCKET] (DEBUG) (JsonAPI.cpp:1099:JsonAPI::handleLoggingCommand()) log streaming deactivated for client  ::1
2021-12-08T22:10:55.297Z [ WEBSOCKET] (DEBUG) (JsonAPI.cpp:1090:JsonAPI::handleLoggingCommand()) log streaming activated for client ::1
2021-12-08T22:10:55.297Z [ WEBSOCKET] (DEBUG) (JsonAPI.cpp:1090:JsonAPI::handleLoggingCommand()) log streaming activated for client ::1

</details>

**Comment by Lord-Grey** [comment] 2022-03-13 16:12
Hi

I retested with the latest WLED version and cannot reproduce the issue.
Maybe you can retest with Hyperion's nightly build to see, if the issue still exists on your end.

I will close the issue for the time being.

**Closed by Lord-Grey** 2022-03-13 16:12 UTC
Labels: Closed
