### ISSUE TITLE
Not listening on any ports on debian buster

### ISSUE THREAD

**Issue by micw** [hyperion-project/hyperion.ng#1237] opened 2021-05-02 18:09 UTC
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

* Do a fresh install of debian 10 for RPi
* Install the 2.0 alpha 9 deb package (https://github.com/hyperion-project/hyperion.ng/releases/download/2.0.0-alpha.9/Hyperion-2.0.0-alpha.9-Linux-armv7l.deb)
* Install additional dependency libfreetype6
* Start hyperiond

#### What is expected?

* Hyperion should listen at some ports, especially 8090 or 8099 for webui

#### What is actually happening?

* Hyperion not listening at any port (check with `netstat -peanut`)

#### System

Debian 10 for RPi 2.

**Comment by micw** [comment] 2021-05-02 18:10
Startup log (with .hyperion fodler removed before start):
```
2021-05-02T18:09:58.516 hyperiond MAIN         : <INFO> Starting Hyperion - 2.0.0-alpha.9, (HEAD detached at 83338dc3) (Paulchen Panther-ca50487e/83338dc3-1605733041), built: Nov 18 2020:22:02:33
2021-05-02T18:09:58.517 hyperiond MAIN         : <DEBUG> main.cpp:384:main() | QtVersion [5.7.1]
2021-05-02T18:09:58.518 hyperiond MAIN         : <INFO> Set user data path to '/root/.hyperion'
2021-05-02T18:09:58.870 hyperiond DAEMON       : <DEBUG> PythonInit.cpp:40:PythonInit() | Initializing Python interpreter
2021-05-02T18:09:59.473 hyperiond SETTINGSMGR  : <DEBUG> SettingsManager.cpp:109:SettingsManager() | Settings database initialized
2021-05-02T18:09:59.474 hyperiond DAEMON       : <INFO> CEC handler created
2021-05-02T18:09:59.511 hyperiond EFFECTFILES  : <INFO> 39 effects loaded from directory :/effects/
2021-05-02T18:09:59.528 hyperiond EFFECTFILES  : <INFO> 22 effect schemas loaded from directory :/effects/schema/
2021-05-02T18:09:59.529 hyperiond EFFECTFILES  : <INFO> New Effect path "/root/.hyperion/custom-effects" created successfully
2021-05-02T18:09:59.599 hyperiond SETTINGSMGR  : <DEBUG> SettingsManager.cpp:109:SettingsManager() | Settings database initialized
2021-05-02T18:09:59.602 hyperiond BLACKBORDER  : <DEBUG> BlackBorderProcessor.cpp:64:handleSettingsUpdate() | Set mode to: default
2021-05-02T18:09:59.603 hyperiond COMPONENTREG : <DEBUG> ComponentRegister.cpp:36:setNewComponentState() | Blackborder detector: enabled
2021-05-02T18:09:59.644 hyperiond DAEMON       : <INFO> set screen capture device to 'dispmanx'
2021-05-02T18:09:59.645 hyperiond DISPMANXGRAB : <DEBUG> Grabber.cpp:30:setVideoMode() | Set videomode to 0
2021-05-02T18:09:59.655 hyperiond LEDDEVICE    : <INFO> Start LedDevice 'file'.
2021-05-02T18:09:59.656 hyperiond LEDDEVICE    : <DEBUG> LedDevice.cpp:148:init() | deviceConfig: [{"colorOrder":"rgb","currentLedCount":1,"hardwareLedCount":1,"latchTime":0,"output":"/dev/null","rewriteTime":0,"type":"file"}]
2021-05-02T18:09:59.656 hyperiond COMPONENTREG : <DEBUG> ComponentRegister.cpp:36:setNewComponentState() | Smoothing: enabled
2021-05-02T18:09:59.656 hyperiond LEDDEVICE    : <DEBUG> LedDevice.cpp:407:setLatchTime() | LatchTime updated to 0ms
2021-05-02T18:09:59.657 hyperiond LEDDEVICE    : <DEBUG> LedDevice.cpp:434:setRewriteTime() | RewriteTime updated to 0ms
2021-05-02T18:09:59.657 hyperiond SMOOTHING    : <DEBUG> LinearColorSmoothing.cpp:701:selectConfig() | cfg [0]:  Type: linear - Time: 200 ms, outputRate 25.000000 Hz, interpolationRate: 25.000000 Hz, timer: 40 ms, Dithering: 0, Decay: 1.000000 -> HalfTime: 100.000000 ms
2021-05-02T18:09:59.657 hyperiond LEDDEVICE    : <DEBUG> LedDeviceFile.cpp:59:open() | QIODevice::WriteOnly, /dev/null
2021-05-02T18:09:59.663 hyperiond SMOOTHING    : <DEBUG> LinearColorSmoothing.cpp:701:selectConfig() | Previous line repeats 1 times
2021-05-02T18:09:59.663 hyperiond FLATBUFCONN  : <INFO> Connecting to Hyperion: 127.0.0.1:19401
2021-05-02T18:09:59.669 hyperiond EFFECTENGINE : <INFO> Run effect "Rainbow swirl fast" on channel 0
2021-05-02T18:09:59.673 hyperiond EFFECTENGINE : <DEBUG> EffectEngine.cpp:183:runEffectScript() | Start the effect: name [Rainbow swirl fast], smoothCfg [2]
2021-05-02T18:09:59.674 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:161:registerInput() | Register new input 'System/EFFECT' with priority 0 as inactive
2021-05-02T18:09:59.675 hyperiond HYPERION     : <INFO> Initial foreground effect 'Rainbow swirl fast' started
2021-05-02T18:09:59.680 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:161:registerInput() | Register new input 'System/GRABBER' with priority 250 as inactive
2021-05-02T18:09:59.683 hyperiond COMPONENTREG : <DEBUG> ComponentRegister.cpp:36:setNewComponentState() | Framegrabber: enabled
2021-05-02T18:09:59.688 hyperiond BOBLIGHT     : <DEBUG> BoblightServer.cpp:28:BoblightServer() | Instance created
2021-05-02T18:09:59.690 hyperiond COMPONENTREG : <DEBUG> ComponentRegister.cpp:36:setNewComponentState() | LED device: enabled
2021-05-02T18:09:59.928 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:351:setCurrentTime() | Set visible priority to 0
2021-05-02T18:09:59.930 hyperiond SMOOTHING    : <DEBUG> LinearColorSmoothing.cpp:701:selectConfig() | cfg [2]:  Type: linear - Time: 200 ms, outputRate 25.000000 Hz, interpolationRate: 25.000000 Hz, timer: 40 ms, Dithering: 0, Decay: 1.000000 -> HalfTime: 100.000000 ms
2021-05-02T18:09:59.933 hyperiond HYPERION     : <DEBUG> Hyperion.cpp:559:handlePriorityChangedLedDevice() | priority[0], previousPriority[255]
2021-05-02T18:09:59.935 hyperiond HYPERION     : <DEBUG> Hyperion.cpp:569:handlePriorityChangedLedDevice() | new source available -> switch LED-Device on
2021-05-02T18:09:59.946 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:251:setInputImage() | Priority 0 is now active
2021-05-02T18:10:02.923 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:315:setCurrentTime() | Timeout clear for priority 0
2021-05-02T18:10:02.925 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:351:setCurrentTime() | Set visible priority to 0
2021-05-02T18:10:02.927 hyperiond SMOOTHING    : <DEBUG> LinearColorSmoothing.cpp:701:selectConfig() | cfg [0]:  Type: linear - Time: 200 ms, outputRate 25.000000 Hz, interpolationRate: 25.000000 Hz, timer: 40 ms, Dithering: 0, Decay: 1.000000 -> HalfTime: 100.000000 ms
2021-05-02T18:10:02.929 hyperiond HYPERION     : <DEBUG> Hyperion.cpp:559:handlePriorityChangedLedDevice() | priority[0], previousPriority[0]
2021-05-02T18:10:03.172 hyperiond HYPERION     : <DEBUG> PriorityMuxer.cpp:351:setCurrentTime() | Set visible priority to 255
2021-05-02T18:10:03.174 hyperiond HYPERION     : <DEBUG> Hyperion.cpp:559:handlePriorityChangedLedDevice() | priority[255], previousPriority[0]
2021-05-02T18:10:03.176 hyperiond HYPERION     : <DEBUG> Hyperion.cpp:562:handlePriorityChangedLedDevice() | No source left -> switch LED-Device off
```

**Comment by micw** [comment] 2021-05-02 18:27
I tried with alpha 5 (which was also on my old installation) with the same results. I'll switch to raspbian.

**Comment by Paulchen-Panther** [comment] 2021-05-02 18:51
Download URL for Debian Buster RPi2 please. Thank you.

**Comment by micw** [comment] 2021-05-02 18:52
I used the image from https://wiki.debian.org/RaspberryPiImages#Installation.
I did a fresh install using raspbian (minimal image) which did not have this issue.

**Comment by DaniloMagliarisi88** [comment] 2021-05-04 21:19
i have the same issue with debian buster, but not with raspberry, but with orangePi. the site can't be reached.

**Comment by Lord-Grey** [comment] 2021-07-18 15:13
Can you re-test with alpha10 and report back please, if the issue is still present?

**Comment by Lord-Grey** [comment] 2021-08-01 19:34
Closing, as no feedback provided. Can be reopened, if needed.

**Closed by Lord-Grey** 2021-08-01 19:34 UTC
Labels: Waiting For Review
