### ISSUE TITLE
Impossible to use hyperion-v4l2

### ISSUE THREAD

**Issue by washcroft** [hyperion-project/hyperion.ng#542] opened 2019-02-25 08:27 UTC
Following @Paulchen-Panther 's latest updates, it is no longer possible to use the hyperion-v4l2 utility as the device name is never set:

```
# hyperion-v4l2 --device /dev/video0

hyperion-v4l2:
        Version   : 2.0.0 (master (GitHub-c2d19063/91054d8d-1550176449) Git Remote: https://github.com/hyperion-project/hyperion.ng.git)
        build time: Feb 24 2019 16:59:47
[hyperion-v4l2 V4L2:/dev/video0] <ERROR> Throws error nr: Cannot identify '' error code 2, No such file or directory
[hyperion-v4l2 V4L2:/dev/video0] <ERROR> Throws error nr: VIDIOC_QUERYCAP error code 9, Bad file descriptor
[hyperion-v4l2 V4L2:/dev/video0] <ERROR> Throws error nr: close error code 9, Bad file descriptor
```

Caused by this commit where the device/input number (from the constructor parameters) are now ignored:

https://github.com/hyperion-project/hyperion.ng/commit/2a77f6f0122691fe1961259178c1ce9d0caca053#diff-aec2cfe446c748ff341302e49e490d6bL33

The V4L2 grabber only works within Hyperion because of the call to setDeviceVideoStandard() which also sets _deviceName.

**Comment by Paulchen-Panther** [comment] 2019-02-25 20:16
I hope it has been fixed in PR #539 . Thanks for your bug report

**Comment by vansoest** [comment] 2019-04-02 16:44
I’ve tried your BugFixes2 branch but it hasn’t fixed the issue:

```
# hyperion-v4l2 -d /dev/video/fushicai_usbtv007
hyperion-v4l2:
	Version   : 2.0.0 (makepkg (GitHub-e4bea694/69ceee8b-1554220455) Git Remote: /home/mediacenter/.cache/yay/hyperion.ng-git/hyperion.ng)
	build time: Apr  2 2019 16:35:30
[hyperion-v4l2 V4L2:/dev/video/fushicai_usbtv007] <ERROR> Throws error nr: VIDIOC_S_INPUT error code 22, Invalid argument
[hyperion-v4l2 V4L2:/dev/video/fushicai_usbtv007] <ERROR> Throws error nr: VIDIOC_STREAMON error code 16, Device or resource busy
[hyperion-v4l2 V4L2:/dev/video/fushicai_usbtv007] <ERROR> VIDIOC_STREAMOFF  error code  16, Device or resource busy
```

**Comment by Paulchen-Panther** [comment] 2019-04-02 17:23
@vansoest Very strange way. Could I get an output from `ls /dev` ?

**Comment by vansoest** [comment] 2019-04-02 18:03
I linked the video0 device via a udev rule to /dev/video/fushicai_usbtv007. It’s not related to the problem, but I agree it’s a special behaivor.

```
​$ ll /dev/video0 /dev/video/fushicai_usbtv007
crw-rw----+ 1 mediacenter users 81, 0  2. Apr 19:24 /dev/video0
lrwxrwxrwx  1 root        root      9  2. Apr 19:24 /dev/video/fushicai_usbtv007 -> ../video0
```

**Comment by vansoest** [comment] 2019-04-02 18:25
```
​$ hyperion-v4l2 -d /dev/video1
hyperion-v4l2:
	Version   : 2.0.0 (master (GitHub-3a8e6dc9/ea044977-1554226519) Git Remote: /home/mediacenter/.cache/yay/hyperion.ng-git/hyperion.ng)
	build time: Apr  2 2019 18:15:06
[hyperion-v4l2 V4L2:/dev/video1] <ERROR> Throws error nr: Cannot identify '/dev/video1' error code 2, No such file or directory
[hyperion-v4l2 V4L2:/dev/video1] <ERROR> Throws error nr: VIDIOC_QUERYCAP error code 9, Bad file descriptor
[hyperion-v4l2 V4L2:/dev/video1] <ERROR> Throws error nr: close error code 9, Bad file descriptor
```

**Comment by Paulchen-Panther** [comment] 2019-04-02 18:43
OK. I found the problem. The V4L2 grabber in hyperiond is never stopped, which also explains the device or resource busy error. If you comment out[ these two lines](https://github.com/Paulchen-Panther/hyperion.ng/blob/BugFixes2/libsrc/grabber/v4l2/V4L2Grabber.cpp#L962-L963) it should work.
But note that this is only a temporary fix at the moment. I will fix this as soon as possible

**Comment by Paulchen-Panther** [comment] 2019-04-02 18:52
> udev rule if it’s interesting for you

thanks for the rule 👍

**Comment by Paulchen-Panther** [comment] 2019-05-04 17:14
Could you please test my new [V4L2](https://github.com/Paulchen-Panther/hyperion.ng) Branch and give me feedback if the problem is solved? Thank you in advance.
Greetings, Paulchen

**Comment by brindosch** [comment] 2019-07-18 20:34
Is this issue finally fixed? I've seen no feedback at the linked PRs
The different naming is indeed tricky.

**Comment by Paulchen-Panther** [comment] 2019-07-18 21:08
From my side already. As described above, i have located and fixed the error. Just missing the feedback of @washcroft and @vansoest

**Comment by Paulchen-Panther** [comment] 2019-08-13 20:05
I will close this issue now because no answer and it has been tested and found to be fixed.
If the problem persists, you can reopen it anytime

**Closed by Paulchen-Panther** 2019-08-13 20:05 UTC
Labels: Backlog
