### ISSUE TITLE
Stuttering with DX or QT screen capture under Windows

### ISSUE THREAD

**Issue by SunnyMoo** [hyperion-project/hyperion.ng#1329] opened 2021-09-10 17:29 UTC
- [x] I confirm that this is an issue rather than a question.

## Bug report
When Hyperion is set to capture screen with DX or QT setting, Windows suffers from stuttering
Changing capture frequency or picture decimation makes no change.
Enable or disable Win10 transparency makes no change.
Tried some changes in nVidia settings made no difference.
Tested with Witcher3 it runs fine with no freeze or fps loss.
Does not happen when using Hyperion ScreenCap instead of Hyperion DX or QT.

#### Steps to reproduce
Go to capturing hardware, enable screen capture, set device discovered to DX or QT.

#### What is expected?
Smooth normal Windows behavior.

#### What is actually happening?
Examples:
- freezes when watching video
- moving windows stutters like there was 30fps but 60fps are actually here

#### System

Hyperion Server:
- Build:             (HEAD detached at 2.0.15) (GitHub-70e1043/24a00e3-1676809483)
- Build time:        Feb 19 2023 14:48:39
- Git Remote:        https://github.com/hyperion-project/hyperion.ng
- Version:           2.0.15
- UI Lang:           en (BrowserLang: fr-FR)
- UI Access:         default
- Avail Screen Cap.: qt,dx
- Avail Video  Cap.: v4l2
- Avail Audio  Cap.: audio
- Avail Services:    boblight,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       C:/Users/.../.hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      Windows 10 Version 2009
- Architecture:      x86_64
- Kernel:            winnt (10.0.22631 (WS: 64))
- Root/Admin:        false
- Qt Version:        5.15.2
- Python Version:    3.11.2
- Browser:           Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0

Thank you !

edit: issue remains with 2.0.15

**Comment by Corbin1747** [comment] 2021-11-03 08:47
I found the same issue. It was caused by a Windows update and Having NG start with windows. Once I disabled auto start up it would work fine when i started it up manually.

**Comment by SunnyMoo** [comment] 2021-11-03 15:15
As expected disabling autostart and starting HyperionNG manually after reboot has no effect on this issue.

**Comment by GreenDie** [comment] 2022-11-29 23:52
Ich habe das selbe Problem. Leichte Erfolge könnte ich du ich ein heruntersetzen der Aufnahmepriorität von 250 auf 100 erzielen.
Ganz verschwindet es allerdings erst wenn ich die aufnahmebildwiederholrate auf 1 setze.
Das ist natürlich ungenießbar.

**Comment by SunnyMoo** [comment] 2022-11-30 00:00
I don't speak german.

**Comment by GreenDie** [comment] 2022-11-30 00:06
I know the solution...
Turn of black black Bars removing.
Or Turn IT top classic

**Comment by GreenDie** [comment] 2022-11-30 13:09
Oh noch i got the Problem again without... I dont know why😭

**Comment by Aasikki** [comment] 2022-12-04 17:45
Any chance for a fix? This is making Hyperion unusable on my system.

**Comment by GreenDie** [comment] 2022-12-04 19:58
Use better CPU.
Set down to 1080p .

**Comment by GreenDie** [comment] 2022-12-04 19:59
Use Prismatik

**Comment by SunnyMoo** [comment] 2022-12-04 20:05
If it's for talking nonsense you should better just shut up and leave this thread to real feedback and solutions.

**Comment by GreenDie** [comment] 2022-12-04 21:40
I have the same problem and am looking for a solution myself!  Why should I talk nonsense?  I've been dealing with the problem for about a year and am just passing on my experience reports.  it helped me to lower the resolution in windows from 2160p to 1080p.  Ultimately it leads back to a performance issue as far as I know.  With my gaming PC (12600+6900xt) I don't have any stutters.  With my Mini PC (4700u) it is... maybe it's because of the missing multithreading... I don't know.  I don't know what CPU you have either.  and I finally try to bring our experiences together so that the problem can be clearly identified.

**Comment by SunnyMoo** [comment] 2022-12-04 21:57
Telling nonsonses:
- "I know the solution" > "oh noes I don't!"
- switch from native resolution to 1080p just for hyperion to work
- use prismatik, it's hyperion here go talk prismatik on prismatik project pages
- use better cpu, so stupid I don't even know what to say

As I now use hdmi to usb-c capture I can't tell if it keeps on stuttering with hyperion's DX/QT capture, but the issue was obviously tied to hyperion and no whatever stupid advice one can spit on tom's hardware forums like "hey dude switch to phillips ambilight lole" "turn off your antivirus" "buy a bigger rig" and so on.

You said you don't know and that may be the only smart thing you did, it's on hyperion devs side to fix this issue, if not fixed yet.

**Comment by GreenDie** [comment] 2022-12-04 22:17
It's not the place to discuss whether I'm talking nonsense...
 I also have a capture card.  However, it also stutters for me when I have activated the USB recording.
 Of course, I also don't believe that it is due to the CPU performance, since Hyperion already runs perfectly on a Raspberry Pi Zero W.
 I am trying to identify the problem.  It would therefore be useful if you provided more detailed information.
 I'll start.
 I start my PC and turn on this [YouTube Video](https://youtu.be/vigX3H7WX5Q) .
 The video runs perfectly without stuttering.
 Now I start Hyperion, the video starts to stutter.  It doesn't matter what video quality I set (2160p or 720p)  The stuttering still persists🤷.  Even if I close Hyperion now: The stuttering stays until I restart the PC!
 Sometimes, I don't know why, the stuttering suddenly goes away.  I can't say exactly what happens to make it go away or what to do to make it go away.  Like when I disabled black bar detection on Wednesday, for example.  Suddenly the stuttering was gone.  The next day I could turn on and off the black bar detection as often as I wanted.  The stuttering persisted.
 The only reliable one:
 I lower the Windows setting from 2160p to 1080p.  The stuttering is gone...

**Comment by GreenDie** [comment] 2022-12-04 22:33
https://photos.app.goo.gl/x1xVboVPz4ADH6aA6
This is what it Looks at me.
Whitch Resolution so you use?
Did it solved the Problem for you to Work with USB Capture?

**Comment by Aasikki** [comment] 2022-12-05 07:27
> Use better CPU. Set Windows resolution down to 1080p .

Ryzen 9 3900X, RTX 2080, 32 GB ram.
I don't think my pc is the issue. Sure I can try to see if lowering my res from 1440p to 1080p helps but that's not a solution, I'm not going to game at 1080p with this monitor and setup even if it helps with this issue. I can stream to discord and use obs without any issues so I can't see why this wouldn't work without stutter as well.

**Comment by Aasikki** [comment] 2022-12-05 07:29
I can post some videos of it too later today!

**Comment by GreenDie** [comment] 2022-12-05 08:54
Ok thank you. I think i know a solition... May Hyperion require all  ,,Microsoft Visual C++ Redistributable“ Versions. I will try my supposition.

I also ordered an HDMI splitter yesterday.  so actually I'm on the way to give up and look for a way out.. I also have to add that "Prismatic" isn't a perfect solution either.  it operates at a variable refresh rate, but browsing still occurs.

But again the question. Does IT solved your Problem to Work with an Capture Card and USB Capture instead of Screen capturing?

**Comment by Aasikki** [comment] 2022-12-05 10:25
> But again the question. Does your Problem was solved by working with an Capture Card and USB Capture instead of Screen capturing?

Even if usb capture "solves" the problem, using screen capture shouldn't cause any issues in the first place.

**Comment by GreenDie** [comment] 2022-12-05 10:39
but since the USB recording caused stuttering for me myself, I suspect the problem elsewhere..

**Comment by Aasikki** [comment] 2022-12-05 10:40
> 

Yeah. Definitely a weird issues though

**Comment by SunnyMoo** [comment] 2022-12-05 14:29
> https://photos.app.goo.gl/x1xVboVPz4ADH6aA6 This is what it Looks at me. Whitch Resolution so you use? Did it solved the Problem for you to Work with USB Capture?
You're GPU limited, period.

> I think i know a solition... May Hyperion require all ,,Microsoft Visual C++ Redistributable“ Versions.
Another stupid statement

> Even if usb capture "solves" the problem, using screen capture shouldn't cause any issues in the first place.
Don't waste your time with this kid, all he said here is plain bullsh*t, my grand'ma knows more about computers.

**Comment by GreenDie** [comment] 2022-12-05 16:09
Yes, I have to revise that again. The problem clearly only occurs with the screen recording.

**Comment by GreenDie** [comment] 2022-12-05 16:46
Have you tested whether my YouTube video also stutters for you or not at all?  And what kind of hardware do you have anyway?

**Comment by GreenDie** [comment] 2022-12-05 17:19
my rtx 2060 stutters and gets also up to 70%..
I think maybe the solution would be to be able to set the resolution of the screen recording and select 720p for example. I don't know if this possibility exists for the developers and I can't program it myself.
Perhaps there would be the possibility of simulating a program that records the screen in 720p which is displayed as a USB recording device in Hyperion...
However, I believe that it would then be easier to buy a capture card with an integrated loop for 15€...
However. I will now go this way by splitting the HDMI signal and feeding it back via USB, which also bypasses the DRM copy protection at the same time. So it's actually a reasonable solution anyway.

Have fun with Hyperion and have a good week

**Comment by SunnyMoo** [comment] 2022-12-05 18:29
> > You're GPU limited, period.
> 
> I dont think the problem is being gpu limited, at least not for me
Don't worry I was talking about greendie, his computer can't support youtube@4K it's not related anyway to hyperion as his system resolution didn't change only youtube streaming format.

In order to check if hyperion's DX/QT capture is involved you can try with hyperion screencap, if it still works I didn't use it for long time.

**Comment by GreenDie** [comment] 2022-12-05 21:09
The stuttering is definitely not due to my system performance :D I tested a system with RTX 2060 and 6900XT.  That doesn't really matter at all!

**Comment by GreenDie** [comment] 2022-12-06 20:35
dear friends, I know the Solution!
[HyperionScreenCapture](https://github.com/sabaatworld/HyperionScreenCap)
install the software 
Enter the IP Adress of yout Computer where Hyperion is installed on
![image](https://user-images.githubusercontent.com/93849179/206017137-54b4896b-1df0-46d2-ad5b-e30ac12b4263.png)
to figure out your IP Adress open CMD and enter `ipconfig`
enable Bolight server
![image](https://user-images.githubusercontent.com/93849179/206016722-314820e4-2de3-401a-8de6-8dfdb26adf97.png)

Have fun!

**Comment by SunnyMoo** [comment] 2022-12-06 22:49
> dear friends, I know the Solution! [HyperionScreenCapture](https://github.com/sabaatworld/HyperionScreenCap)

Seriously kid just get lost in the depths of the Schwarzwald and stop polluting this thread !
I've talked about hyperion screencap since the very first post and **this is no solution**, it's a workaround.

**Comment by SunnyMoo** [comment] 2022-12-07 19:25
Stating the obvious is not helping. Spamming nonsenses is pollution. I'm not toxic I just give him the patience he deserves.
If I opened this ticket and kept subscribed it's not to deal with trash flooding 1 digit IQ kids.
The only one(s) who can bring a solution to this issue is(are) the dev(s).

**Comment by Aasikki** [comment] 2022-12-07 19:27
> I'm not toxic

Says the man while being incredibly toxic lmao.

**Comment by SunnyMoo** [comment] 2022-12-07 19:29
Believe me I can be far worse :p

**Comment by holzmichlnator** [comment] 2023-01-10 01:02
I have exactly the same problem. This is especially noticable on a 120hz display. Just grab a random window like a windows explorer window and move it around. It will stutter like hell. As soon as you quit hyperion, the stuttering is gone.

Changing the capture method from QT to DX doesn't change anything. Disabling the screen capturing completely does "fix" the stuttering. 

But @GreenDie is right, using [HyperionScreenCapture](https://github.com/sabaatworld/HyperionScreenCap) works like a charm. Just disable screen capturing in Hyperion and setup and start HyperionScreenCap and everything works without stutter. 

It would be nice to have this fixed in hyperion itself. Using HyperionScreenCap is just a work around imho. 

Another nice thing to mention is that HyperionScreenCap uses a lot less CPU and GPU resources then Hyperion itself. But i haven't had the chance to test this over a longer priod of time and in some games yet.

**Comment by kekkokk** [comment] 2023-03-23 23:22
> I have exactly the same problem. This is especially noticable on a 120hz display. Just grab a random window like a windows explorer window and move it around. It will stutter like hell. As soon as you quit hyperion, the stuttering is gone.
> 
> Changing the capture method from QT to DX doesn't change anything. Disabling the screen capturing completely does "fix" the stuttering.
> 
> But @GreenDie is right, using [HyperionScreenCapture](https://github.com/sabaatworld/HyperionScreenCap) works like a charm. Just disable screen capturing in Hyperion and setup and start HyperionScreenCap and everything works without stutter.
> 
> It would be nice to have this fixed in hyperion itself. Using HyperionScreenCap is just a work around imho.
> 
> Another nice thing to mention is that HyperionScreenCap uses a lot less CPU and GPU resources then Hyperion itself. But i haven't had the chance to test this over a longer priod of time and in some games yet.

I found myself in the same situation. 
With the embedded screen capture, things like moving windows in the desktop or also playing game results in slighlty stuttering like I am running on 60hz.
I think this is related to the fact that I'm running on a 160hz display but the maximum capture rate I can set inside the app is capped at 60hz and it reflect this "mismatch" to the windows I move.

But, as someone suggested, does not happen if using external HyperionScreenCap standalone software and works like a charm.
Love to see this fixed

**Comment by Gremious** [comment] 2024-02-29 21:01
HyperionScreenCapture fixes the stutter, but it wasn't a great solution for me because it seems to disrespect the whites/hyperion calibration on my nice RGBA-WW LED's.

On the other hand, the [HyperHDR](https://github.com/awawa-dev/HyperHDR) seems to work without any secondary app running and using the proper whites (And I don't really use an HDR monitor or anything).

**Comment by Paulchen-Panther** [comment] 2024-03-01 07:55
> On the other hand, the [HyperHDR](https://github.com/awawa-dev/HyperHDR) project seems to work without any secondary app running, and using the correct white color by default (and I don't really use an HDR monitor or anything).

philips ambilight also works with correct white.

**Comment by SunnyMoo** [comment] 2024-03-01 17:16
Solution is to use HyperHDR, use it for years now and it's better in any terms.
/thread

**Closed** 2024-05-30 11:39 UTC
Labels: Improvements
